### PR TITLE
Use try-with-resources.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
[Try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) is supported on API levels below 19 when Java 8 support is enabled.

### CODE REVIEW

**Comment by westnordost** [comment]
Looks reasonable. Did you test it? Both places are critical places within the app, an error there will have very serious consequences (data corruption).

**Comment by Isira-Seneviratne** [comment]
> Looks reasonable. Did you test it? Both places are critical places within the app, an error there will have very serious consequences (data corruption).

I tried updating a note and didn't encounter any crashes or anything like that.

**Comment by westnordost** [comment]
Mh, the serializer is only used for notes if you attached a picture to the note

**Comment by Isira-Seneviratne** [comment]
> Mh, the serializer is only used for notes if you attached a picture to the note

Oh, I see. In that case, what about when adding road information?

**Comment by westnordost** [comment]
Yes, solving a quest and uploading the change should be enough as it serializes the changes once and then deserializes it for upload. If the upload is correct, then the change did not create any problems

**Comment by westnordost** [comment]
Is that what you meant with "adding road information"?

**Comment by Isira-Seneviratne** [comment]
> Is that what you meant with "adding road information"?

Yeah.

**Comment by westnordost** [comment]
Ok, then this is safe. Thank you!

**Pull request merged**
