### PR TITLE
Better lighting changeset commit message wording

### PR DESCRIPTION
**Pull request by gileri**
Currently the message for this quest is "Add way lit", which is poorly phrased.
This PR changes it to "Add way lighting".

### CODE REVIEW

**Comment by ENT8R** [comment]
BTW: In https://github.com/westnordost/StreetComplete/pull/424#discussion_r130040357 @westnordost said:

> I'd prefer "lit" because that is the tag that is being set and anyone who is reading the changesets will know immediately what it is about. Perhaps also change the quest name in code.

**Comment by gileri** [comment]
In the comment you linked the original message was "Add way light", which I understand could mean "adding light poles". I'm not sure it's the case for "Add way lighting".

Should we use "Indicate whether way is lit", "Add whether way is lit" or "Set lit tag to way" then ? They seem more contrived but could work.

**Comment by westnordost** [comment]
The second sounds good to me

Am 20. Mai 2018 13:30:09 MESZ schrieb "Eric G." <notifications@github.com>:
>In the comment you linked the original message was "Add way light",
>which I understand could mean "adding light poles". I'm not sure it's
>the case for "Add way lighting".
>
>Should we use "Indicate whether way is lit", "Add whether way is lit"
>or "Set lit tag to way" then ? They seem more contrived but could work.

**Comment by gileri** [comment]
Sorry I'm not sure, do you mean "Indicate whether way is lit" or "Add whether way is lit" ?

**Comment by westnordost** [comment]
I like "Add" better because this is then consistent with the other commit messages.

**Pull request merged**
