### PR TITLE
Don't show gap in SlidingRelativeLayout (Fix #841)

### LINKED ISSUE #841: Quest UI - Bottom, Slice of the Map
Hey,

just updated to 4.0beta01 - I noticed that there is a small slice of the map at the bottom of the quest UI.

Is this intended? Or even a new feature?

See https://lut.im/ydHhb5BSlA/Q5PzzVkENLOdn4Pd.png

Keep up the the good work! :relaxed:

### PR DESCRIPTION
**Pull request by ENT8R**
Fixes #841

### CODE REVIEW

**Comment by westnordost** [comment]
:-)

**Comment by westnordost** [comment]
I read a bit into the topic and discovered this: https://stackoverflow.com/a/15301092

I am currently trying out if the solution proposed there has any sideeffects. If it doesn't, would you also try it on your phone?

**Comment by westnordost** [comment]
Actually, the `post()` thingy did not work. But I fixed two bugs and added the getters again in your code.

**Comment by ENT8R** [comment]
Great! Thank you!

**Pull request merged**
