### PR TITLE
add link to OSM notes

### PR DESCRIPTION
**Pull request by matkoniecz**
if desirable I may make a guide about how SC notes may be processed

### CODE REVIEW

**Comment by rugk** [comment]
The link you give there, actually loads quite long, so this may not be desirable. Maybe limit the map or so in that link.

**Comment by westnordost** [comment]
I added some more text and changed the link as suggested by rugk

**Comment by rugk** [comment]
It would have maybe been enough to change `start=true` to `start=false` or so. Because now it does not autofill "StreetComplete".

BTW just noted the application does always search worldwide, so…

**Comment by westnordost** [comment]
Whoopsie, corrected

**Pull request merged**
