### PR TITLE
Add a quest for missing public_transport tag on bus_stop

### PR DESCRIPTION
**Pull request by nlehuby**
with a big thanks to @ENT8R

### General
Affected key(s) (or tags) to be modified: [public_transport](https://wiki.openstreetmap.org/wiki/Key:public_transport)
Question asked: **Is it where the bus stops on the road, or where passengers wait for their bus??**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### CODE REVIEW

**Comment by westnordost** [comment]
Please excuse my brevity, I am on awfully long bus ride from Chiang Mai to Bangkok, so I decided to look through some PRs here.

Thank you @nlehuby, for your effort, but I fear I won't merge this pull request. The reason is that the kind of information that is asked for can also be found out automatically, by analysing whether the node is on the road-way or beside it instead of (a little awkwardly) ask a surveyor, can it not?

Additionally, this quest looks basically like an attempt to translate the public transport scheme from v1 to v2. Though, more than just adding this one value is necessary to do that to make a complete conversion - conditionally adding the platform node, moving the tags from one node to another, adapting enclosing relations, removing the v1 tagging, etc. - something that can better be done with a proper editor.
I strongly feel that any bus line/stop tagging should either be v1 or v2 (or v3, 4,...), not both at the same time.

I am sorry that I did not make that clear in the contribution guidelines, I will add a few sentences there.

**Comment by nlehuby** [comment]
Thanks for your feedback.

This is not an attempt to convert from schema v1 to v2.
By the way, the ptv2 proposal clearly states :

> "This proposal does not replace, deprecate or obsolete the already existing and well known tags"
> "The proposed tags can and do coexist with the well known tags."

source: https://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport

Prior to the ptv2 proposal, the bus stop definition is OSM was unclear and some people mapped them 
as a node on the side of the road where the people wait whereas others have been mapped as a node on the road itself where the vehicle stops.
The situation did not change that much since the proposal, so this quest is about making a difference between bus stops mapped beside the street and bus stops mapped on the street.

And many of the bus stops mapped on the street are not part of the way of the street (probably because this is not an easy thing to do in most editors). These cannot be found automatically so easily. 
We can adjust the overpass query to only ask if
* this is a node 
* with a highway=bus_stop tag
* without any public_transort tag
* and it is not part of any way

Would it be better ?

**Comment by westnordost** [comment]
> This is not an attempt to convert from schema v1 to v2.

Well, highway=bus_stop is v1, public_transport=X is v2. In my definition, this is a conversion.

I interpret the sentence you cited from the wiki like that v2 does not deprecate v1, in that i.e. one bus stop may be mapped in v1, another in v2, and that'd be okay.
However, I was speaking about mixing v1 and v2 in **one** and the same node being an undesirable thing. Mixing tagging schemes is undesirable in general, not limited to the different pt-versions, because it at best adds duplicate information and at worst adds contradictory information. 
(This might or might not be my personal opinion as a software developer on that topic, I did not search if the topic came up in mailing list discussions or in the wiki.)

Anyway, this is not really the main issue here. The issue is, I cite myself from the previous reply:

> [...] the kind of information that is asked for can also be found out automatically, by analysing whether the node is on the road-way or beside it instead of (a little awkwardly) ask a surveyor [...]

In other words, you don't need a surveyor to get this kind of information, just check if the node is part of the road or not.

See also the wiki page linked by you. It clearly specifies rules for data consumers working with v2 how to interpret v1 data:

| Existing tag	| Interpretation	 | Comment |
| --- | --- | --- |
| highway=bus_stop beside a way/street where buses are allowed	| public_transport=platform	| This covers the pole/shelter of a bus stop and can be on a footway or sidewalk. |
| highway=bus_stop on a way/street where buses are allowed	| public_transport=stop_position + bus=yes |

I think the point you made in your last reply was that sometimes there may be highway=bus_stop nodes visibly on the road but not part of the road-way because of deficiencies of certain editors, right?
Well, what should a surveyor answer in this case that couldn't just as well be determined automatically by measuring the distance between the node and the road? After all, the surveyor also just sees the point on the map.

But anyway, I'd say a node is not part of a road-way, can never be a stop position, thus the cited v1 interpretation from the wiki applies regardless of the distance of the node to the way.

**Comment by westnordost** [comment]
I was missing a "that" in my last sentence there, GitHub on a mobile device doesn't let me edit the reply.

**Comment by HolgerJeromin** [comment]
In my interpretation there should be the old `highway=bus_stop` for backward compatibility and the new `public_transport=*`.
This is supported by this [wikipage](https://wiki.openstreetmap.org/wiki/Public_transport#Buses)
> Note: Because the newer public_transport=* tags are currently not rendered on the main page, the bus stops have to be additionally tagged with highway=bus_stop (see bug report).

**Comment by rugk** [comment]
> BTW you can change the mobile page to desktop view with the link on the bottom. Not nice but a way to edit on mobile.

Or use [FastHub (Libre)](https://f-droid.org/packages/com.fastaccess.github.libre/).

**Comment by nlehuby** [comment]
public_transport = platform is a generic tag for every kind of platform ever. If used alone, you cannot say if this is a bus stop or a tram one, etc.
OSM Inspector and Osmose QA already have dedicated test on this very subject : highway=bus_stop without any public_transport tag


Yes, we could use the distance to the road to guess if this should be platform or a stop_position, but that would lead to automated edits !  
We value local and ground-approved data over all, don't we ?

**Comment by rugk** [comment]
Indeed, I'd also say guessing this is not appreciated in the osm community. Also automated edits are often discouraged too.

I think this quest here is really easy to answer and is only asked when the node"s tagging is incomplete.
Of course, it should not convert v1 to v2. So it should only trigger when a v2 node is incorrect.

**Comment by westnordost** [comment]
@nlehuby Not sure if you got my point. Please read my post again carefully from _"Anyway, this is not really the main issue here. The issue is, I cite myself from the previous reply:"_ onward to make sure and post here again if you don't see that you missed it.

**Comment by westnordost** [comment]
But first:
> I think the point you made in your last reply was that sometimes there may be highway=bus_stop nodes visibly on the road but not part of the road-way because of deficiencies of certain editors, right?

Did I understand **your** point?

**Comment by nlehuby** [comment]
Not exactly:

I don't blame any editor here. Public transport mapping is not easy and I honestly think we can explain most of the inconsistencies in our data by the fact that the mapper does not know the best practices to properly add a bus stop. 

You can find `highway=bus_stop` on the road, but not part of the road way. And it may be because of the editors, as most of them do not allow this kind of modification.
But you can also find the opposite: `highway=bus_stop` part of some `highway` way and that should actually have a `public_transport = platform` tag (because it is a pedestrian way, or a `highway=platform`)

In my experience, trying to guess how to automatically add tag always turns wrong, as you cannot predict what exceptions you will get from the data.
A good way to handle that is 
* to modify individual points, relying on ground survey
* to educate about the good practices

And I really think StreetComplete can help: for instance, the quest about the pedestrian crossing made me realized how many crossings in my neighborhood were outdated in OSM and do not exist anymore, and also lead me to learn how to map crossings, to add the missing ones.

But I don't deny this: this quest is not very rewarding, and it's mainly about correcting inconsistencies in our way to map bus stops.

**Comment by westnordost** [comment]
> In my experience, trying to guess how to automatically add tag always turns wrong, as you cannot predict what exceptions you will get from the data.

Both you and rugk seem to think that I was talking about automated edits when presenting the table above from the wiki. I meant, this "guessing" needs to be done by the data consumers who implement the public transport scheme.

Anyway, I think I now have all information I need. I'm sorry, my decision is to not merge this PR. The decision has been made, but I would like to that you understand why not. So again, here is why:

The information collected with this quest can by definition from the wiki be inferred automatically from the v1 scheme, as mentioned in https://github.com/westnordost/StreetComplete/pull/725#issuecomment-353965077 : if the `highway=bus_stop` is part of the way, it is to be treated as a stop position, if not, it is to be treated as the platform by data consumers.

In the case (you described) that the bus stop node was _meant to be_ the stop position and not the platform but for some reason is not part of the way (or the other way round), a survey with StreetComplete will not solve the problem because
1. StreetComplete does not alter the geometry, but it would be necessary: A stop position that floats free next to the bus route is useless. A platform that is glued on the bus route is contradictory at best. Whatever is added through this app that does _not_ coincide with the interpretation from the table above will actually make the data _worse_, in that it adds inconsistencies!
2. The stop position is perhaps 2-3m away from the platform node. There is no way the user of the app who just sees his own GPS position (which is often not that precise on the go) and the position of that node on his smartphone map and has nothing more to go on can safely determine whether this point lies on the street or on the sidewalk.

Whoever feels inclined to correct this is, is better of with satellite imagery and an editor with which one can actually move nodes around, glue to/unglue from a way and move tags from one node to another if necessary (i.e. bus stop name from stop position into a nother platform node, relation or whatever).

**Pull request closed without merging**
