### PR TITLE
Add icons for museum and beer quest

### PR DESCRIPTION
**Pull request by ENT8R**
This PR adds two new icons. And this is how they look like:
icons

I didn't export them to an android vector drawable yet, because I faced some problems while doing this (width and height was different than the other icons)...

### CODE REVIEW

**Comment by westnordost** [comment]
Sorry, I already created an icon for museum (and some others) but did not push it yet.

So, only the beer icon would be fine, though I am really not sure about that quest anyway. Doesn't hurt of course to have an icon for that, just in case.

**Comment by ENT8R** [comment]
Ah! Alright. I'm going to remove the museum icon then.

**Comment by ENT8R** [comment]
I have got one more question: How do you convert the SVG to an Android Vector Drawable? I am using the built-in feature of Android Studio but that does generate code looking always different than the drawables you converted...

**Comment by rugk** [comment]
So can you push in the icon for the museum icon?

**Pull request merged**
