### PR TITLE
Expand leaf type quest to also include tree rows

### LINKED ISSUE #1688: Expand leaf type quest to also include tree rows
**Use case**
Same as leaf type for Forests/woods

**Proposed Solution**
Since there was already discussion on doing single trees which was rejected
This should be acceptable since tree rows are usually relatively big

### PR DESCRIPTION
**Pull request by MegaArthur**
Closes  #1688

### CODE REVIEW

**Comment by westnordost** [comment]
For tree rows, it would probably make sense to enable the possibility to split ways right? Could you add this and test that it does not affect the area-types?

**Comment by MegaArthur** [comment]
> For tree rows, it would probably make sense to enable the possibility to split ways right? Could you add this and test that it does not affect the area-types?

Is just the override required to enable way splitting?

**Comment by matkoniecz** [comment]
To enable way split? Yes. But note "test that it does not affect the area-types".

**Comment by MegaArthur** [comment]
Okay, going to test it tomorrow or the day after

**Comment by MegaArthur** [comment]
@westnordost Tested, the way split appears on tree rows but not forest areas, all is good.

**Comment by westnordost** [comment]
Nice, good! Thanks for the PR!

**Pull request merged**
