### PR TITLE
quest to add leaf_type to trees

### PR DESCRIPTION
**Pull request by matkoniecz**
Is it a good idea to create a new layout for cases where there is small number of choices, like here?

Where I should put credit for authors of images (in one case it is required by license) (I looked at #303, #231 - and it seems that so far only images that does not require attribution were used)? Should I use https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/authors.txt for that?

Where I should put original images to make possible to generate larger images in future, as it will be probably useful for supporting new hardware?

implements part of #83

streetcomplete

### CODE REVIEW

**Comment by westnordost** [comment]
Is this quest worth the effort? Right now, it is not good. If yes, I have the following feedback:
- a proper icon for the quest is missing
- I suggest to either use clear icons or use more representative photos. At least the broadleaved ones is bad (it shows pullulating leaves, that's very specific). Using icons makes it clear what the common factor is (🍂)
- is needleleaved a word? Please use a better wording, i.e. just "needles" and "normal" or something or no words at all
- yes, the layout looks bad. Consider: The height of it all should be small enough that no scrolling is necessary at all. The width should be used fully. For implementation, I strongly recommend not to inherit from ImageListQuestAnswerFragment but configure an own ImageSelectAdapter in your form because much of the complexity in the former is not necessary. Another option: Do not use any RecyclerView, just create a static layout with two selectable images. Whatever is less complex and more readable in the end.

**Comment by westnordost** [comment]
Fyi, I added a "leaf" quest icon

**Comment by loominade** [comment]
Since there is not much to do in parks yet, I think this is a great idea. 

You could use the android emojis for the selection:

 Broadleaved | Needleleaved 
-------------|----------------
 Needle | Broad

**Comment by rugk** [comment]
Any news here? Personally I like @loominade's idea too. You do not always have to have a picture of the leaf, the silhouette of the tree also is a clear indicator for broad-/needleleaved – if the user should only differ between these two items.

**Comment by rugk** [comment]
@westnordost closed because of…?

**Comment by westnordost** [comment]
Because he was not going to finish it.

**Comment by rugk** [comment]
Can't you overtake that PR?

**Comment by westnordost** [comment]
No

**Pull request closed without merging**
