### PR TITLE
Update a few libraries

### PR DESCRIPTION
**Pull request by TacoTheDank**
From https://github.com/westnordost/StreetComplete/pull/2022

- Use Kotlin JDK8
- Update RTL-Viewpager 1.0.2 -> 2.0.0 ([changelog](https://github.com/duolingo/rtl-viewpager/blob/master/CHANGELOG.md))
- Update YAMLBeans 1.13 -> 1.15 ([changelog](https://github.com/EsotericSoftware/yamlbeans/releases))

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
AFAIK, `kotlin-stdlib-jdk8` only introduces extensions for Java 8-specific APIs, such as the Streams and Date/Time APIs.

**Comment by westnordost** [comment]
Ok! Since the RTL viewpager update is a major one, did you test it? It is used in the opening hours quest (when selecting start and end time).

**Comment by westnordost** [comment]
I made the mistake before to trust that minor updates don't break anything, so I always test before updating dependencies, especially if it is just one of many open source libraries not distributed by a big entity like Google.

**Comment by TacoTheDank** [comment]
@westnordost I see. I'll get to testing it when I have the time.

**Comment by TacoTheDank** [comment]
@westnordost Built a debug APK and tested. It works perfectly fine as far as I can tell. Here's the APK in case you'd like to test as well. https://mega.nz/file/8CQmCQwb#aFWdAB5A72qzmvx0X_yrKMtnTibOAHfVsz1QlUlE358

**Comment by westnordost** [comment]
Then it can be merged, thank you!

**Pull request merged**
