### PR TITLE
stop creating quests for private pitches

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes handling of pitches inaccessible to public - for example pitches inside school

https://www.openstreetmap.org/note/1267483 is an example

it is quite rare, but without that in some location SC would be infinite source of notes

### CODE REVIEW

**Comment by rugk** [comment]
Bus in your example one could guess/see (over the fence) what is played there. You'll certainly also see in a school whether they play basketball or football there.

**Comment by matkoniecz** [comment]
Look again at that example. It is inside school, with building around - not just a fence.

It will exclude some private pitches that are visible over the fence but (1) private pitches are typically not tagged with access tag so loss will not be huge (2) it is better to avoid false positives at cost of false negatives.

**Comment by matkoniecz** [comment]
If there is some viable alternative then I would update the PR but I am not aware about anything else that may be checked (I think that checking topology is not a viable solution)

**Comment by westnordost** [comment]
Makes sense

**Pull request merged**
