### PR TITLE
 make questions signs more visible in the sidewalk and cycleway quest [ready for review]

### PR DESCRIPTION
**Pull request by matkoniecz**
only one tester was solving this quest type (as the first ever in her case)
and it went like this

- select this quest
- see road with no sidewalk
- select no sidewalk
- tap outside quest

More visible question signs may help to avoid this mistake as it will be more obvious that both sides should be filled to solve this. Current ones are not clearly visible for someone with poor eyesight or in a glaring sun.

-----

My work on this pull request and UX testing was sponsored by a NGI Zero Discovery [grant](https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/368849)

### CODE REVIEW

**Comment by matkoniecz** [comment]
Note that this quest, unlike some other, is not providing feedback on closing after providing input. I am currently debugging it.

**Comment by westnordost** [comment]
I had the question mark only as an outline to emphasize it is only a placeholder. If you change the question mark for the sidewalk, you should also change it for all other places where such a "street selection puzzle" is shown.

Though, generally, if it is potentially unclear for users how to use the UI, a short hint in the form of one sentence (something like: "Tap the question marks(s) to answer for each side") at the side somewhere could be helpful as well. And/or a pressed-feedback with a ripple effect (starting with v21).

**Comment by matkoniecz** [comment]
> a short hint in the form of one sentence (something like: "Tap the question marks(s) to answer for each side") at the side somewhere could be helpful as well.

I also thought about it but hoped that this change will be enough to make it accessible.

> I had the question mark only as an outline to emphasize it is only a placeholder.

In this case I think that meaning of question mark is quite strong already and it will be not diluted by making it clearly noticeable.

In strong sun it was nearly invisible and easy to miss. I suspect, but not tested, that it is likely to be problem even with a good lighting for someone with poor eyesight.

**Comment by westnordost** [comment]
Ok. It would be good then however to also change it in the source files (the SVGs)

**Comment by callis** [comment]
Another idea would be to change the color of the missing road side. Like it is done in webforms when I missed to fill my phone number.

**Comment by matkoniecz** [comment]
> Ok. It would be good then however to also change it in the source files (the SVGs)

Where this source files are located? I tried `find *| grep .svg` and found svgs in `res` folder, where none matched this produced image.

**Comment by goldfndr** [comment]
https://github.com/westnordost/StreetComplete/blob/master/res/cycleways.svg has the outlined question marks at the top.

**Comment by matkoniecz** [comment]
Thanks! I missed it completely and I looked at this file.

**Comment by westnordost** [comment]
Merged, thank you!

**Pull request merged**
