### PR TITLE
Display housenumbers and bus stops on basemap

### PR DESCRIPTION
**Pull request by Teester**
This pull request modifies the cinnabar basemap style to display house numbers, building names and bus stops on the base map. Resolves issue #162.

Since there are quests to add house numbers and details about bus stops, it seems reasonable to me that these details should be visible on the base map.  Additionally, it may make orientation easier.  However, it does involve modifying the default cinnabar style, which may make updating to new upstream releases, while maintaining these changes, more difficult.

There are a couple of possible issues with these changes:
1. A possible bug in tangram-es prevents '\n' being interpreted as a line break (it works in Tangram Play on the web, but not in the app), so I've opted to display building name in preference to house number in cases where both of these exist.  This is an assumption on my part that building name tends to be more important than building number.
2. These items are only displayed from z18 onwards.  This may or may not be an appropriate zoom level to begin displaying at.
3. Quests will prevent the items from being displayed. For example, the quest marker for a bus stop quest will be displayed, but the bus stop symbol at that particular location won't.  This might not be a bad thing, however.
4. There will be a delay between submitting quest answers (for house numbers, at least) and the information being visible on the basemap due to mapzen not immediately updating their tiles. 

Screenshots:
Before:
screenshot_2017-05-26-12-42-53

After:
screenshot_20170527-004627

### CODE REVIEW

**Comment by matkoniecz** [comment]
Have you tried submitting this pr to the style itself? After I created issue for wall display they added it even without pr (as it was a bug). Merging to upstream is better than maintaining a form.

**Comment by matkoniecz** [comment]
See for example https://github.com/tangrams/cinnabar-style/issues/26

**Comment by westnordost** [comment]
See @matkoniecz 
The cinnabar style should be considered more or less read only. Maintaining a fork of this here adds too much maintenance work. I'd like to encourage you start a new very simple SC style from scratch, that only displays the information needed specifically for this app. This will be easy to maintain as well.

Bus stops should not be shown on the StreetComplete map (why should they be shown?).

**Comment by Teester** [comment]
No problem. I can understand the burden of maintaining a fork of what is a pretty complicated style.  I would, however, suggest that you consider the global options in the style where they are relevant (switching on building name and numbers, for example)

I've submitted some issues and PRs upstream.

I would feel that bus stops would be appropriate to show on the StreetComplete basemap because there are quests specifically dealing with bus stops and their visibility would help determine which bus stop the quest refers in situations where there are multiple stops close together.  It may also help with orientation when walking around.

Is there an issue to discuss what should/should not be displayed in a potential SC style and how they should look?

**Comment by westnordost** [comment]
Thank you for understanding.

I wrote a bit about what a custom style would need (and what it doesn't need ;-) )
https://github.com/westnordost/StreetComplete/issues/183

If you are interested, I can write down some more requirements. But basically, it is a simplistic map from which one can start and then later add more features along the way, such as to customize colors, 3d buildings, housenumbers and so on.

**Pull request closed without merging**
