### PR TITLE
WIP: Add initial Room support.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Add a `RoomDatabase` implementation, migrations and entities, and switch to `SupportSQLiteOpenHelper`. This PR is limited to those changes to keep it as simple as possible, with the intent being to fully switch to Room over multiple PRs: https://medium.com/androiddevelopers/incrementally-migrate-from-sqlite-to-room-66c2f655b377.

### CODE REVIEW

**Comment by matkoniecz** [comment]
Why migrate from SQLite to Room? (sorry if that is obvious, but I lack knowledge here)

**Comment by Isira-Seneviratne** [comment]
> Why migrate from SQLite to Room? (sorry if that is obvious, but I lack knowledge here)

[Room](https://developer.android.com/training/data-storage/room) provides an abstraction layer over SQLite, so performing CRUD operations can be done without having to write boilerplate code.

**Comment by matkoniecz** [comment]
I am NOT experienced in this area, bur from my perspective entities and other Room-specific code is a boilerplate. What worse it is sn Android specific boilerplate rather than universal and clear SQL, adding even more unclear layers of abstraction.

(though my experience here is minimal, I am curious about what @westnordost thinks about this)

**Comment by Isira-Seneviratne** [comment]
> I am NOT experienced in this area, bur from my perspective entities and other Room-specific code is a boilerplate. What worse it is sn Android specific boilerplate rather than universal and clear SQL, adding even more unclear layers of abstraction.
> 
> (though my experience here is minimal, I am curious about what @westnordost thinks about this)

I meant that manually writing code using `Cursor` and `SQLiteOpenHelper` isn't required.

**Comment by westnordost** [comment]
Thank you for your effort, @Isira-Seneviratne , but I fear you could have saved yourself this effort.

I am with @matkoniecz here. The database layer is already well readable and quite short in terms of code thanks to some convenience extension functions. Room may make access for CRUD operations even shorter, but introduces a new framework. The more frameworks there are, the more frameworks (new) contributors need to learn to use and understand, thus increases the entry barrier to contribute to this project. And of course, adding new dependencies has always downsides as well as one becomes dependent on that that dependency may have bugs and may not be properly maintained (one day). (Though since it is from Google, not that much concern here.)

Additionally, to keep options open for a possible port to iOS, if any abstraction layer is introduced, it should actually be one without external dependencies on a Java-library, let alone a Java-library dependent on the Android environment.

Looking at the code of this PR itself, there are a few more reasons not to use this, but the other reasons states should be enough.

**Comment by Isira-Seneviratne** [comment]
> Thank you for your effort, @Isira-Seneviratne , but I fear you could have saved yourself this effort.
> 
> I am with @matkoniecz here. The database layer is already well readable and quite short in terms of code thanks to some convenience extension functions. Room may make access for CRUD operations even shorter, but introduces a new framework. The more frameworks there are, the more frameworks (new) contributors need to learn to use and understand, thus increases the entry barrier to contribute to this project. And of course, adding new dependencies has always downsides as well as one becomes dependent on that dependency - it may have bugs and may not be properly maintained (one day). (Though since it is from Google, not that much concern here.)
> 
> Additionally, to keep options open for a possible port to iOS, if any abstraction layer is introduced, it should actually be one without external dependencies on a Java-library, let alone a Java-library dependent on the Android environment.
> 
> Looking at the code of this PR itself, there are a few more reasons not to use this, but the other reasons stated should be enough.

Okay, I see.

**Pull request closed without merging**
