### PR TITLE
Updates to Cinnabar themes (upstream PRs also submitted)

### PR DESCRIPTION
**Pull request by dbdean**
I understand this might be a little contentious based upon some past issues, but I think that having a basemap that looks like a real map is important (particularly when we can start placing custom notes anywhere).

In particular, seeing the housenumbers on buildings can be very useful when GPS is poor, and you don't know which building you are talking about for height quests, etc.

So, I have made some tweaks to the cinnabar styles and/or the way that StreetComplete is using them, complete with upstream PRs and issues to ensure that we don't end up maintaining too much of this ourselves.

So, a summary of the changes:

1) I have moved to the `label-11.yaml` theme of the cinnabar style that displays most labels and many POIs on the map (including bus stops!) (I have added an issue about this being better documented for cinnabar at https://github.com/tangrams/cinnabar-style/issues/51)

2) Although the above style shows address numbers, it doesn't show them until z20, which is ridiculous, so I have modified them to appear at zoom 17 and submitted a PR to get a similar change in the main style at https://github.com/tangrams/cinnabar-style/pull/52

3) I have made the new default building height more sensible (20 metres is too high, when surrounding heighted-buildings might only be 5-8 metres for 1-2 stories). Upstream PR: https://github.com/tangrams/cinnabar-style/pull/54

4) And finally, the new style shows traffic signals, but they had an ugly white border, so I removed the border from the icon sprite sheet. Upstream PR: https://github.com/tangrams/cinnabar-style/pull/53

### CODE REVIEW

**Comment by westnordost** [comment]
Wait, stop!

Did you read #271 / #183 ?

The situation did not change since then.

To repeat: 
I am not willing to maintain a fork of cinnabar here, with its 4k+ lines of code. Most of the stuff in that theme is not relevant for surveying with SC for OpenStreetMap. I just have (a considered read-only) cinnabar theme here because this is kinda the "default" style, but it is only meant to be there temporarily. Cinnabar works fine for now and updating cinnabar from upstream is okay.

The target is to have an own simplistic stylesheet, built from the ground up, which contains only the elements that are relevant for this app. (I just don't have time for that, so I did not come around to it yet.)
Not sure if I mentioned the reasons for having this simplistic stylesheet yet, so:
- simplistic map does not distract from the app's sole purpose
     - leads to cleaner UI, in focus are the quests
     - Also important to make clear to users on first glance, that SC is not a map app
- (more easily) maintainable, I expect something around 500 lines of code
- can be themed to fit into the theme of the app (i.e. colors like in [Tron](https://tangrams.github.io/tron-style/#15/37.7926/-122.4003) or Pokemon Go. The map can look more playful/gamey and less like a map app as mentioned above
- can be dynamically extended based on the quests that are shown

**Comment by dbdean** [comment]
I have read those issues (they were what I was referring to as "contentious based upon some past issues"), but I respectfully disagree in some aspects.

1. I have sent these changes upstream to the cinnabar theme, and am happy to wait for them to accept them before this PR is accepted. At that point, it would just be a new version of cinnabar, and this PR would have no extra maintenance burden over the status quo.

2. This may be an expert vs beginner mapper thing, but I think StreetComplete works well with a reasonable complete basemap (which it currently has), and I think that moving to a more abstract map would be a poor choice, and would certainly increase the maintenance, because then you would have to maintain your own map style (and any non-trivial map style will always be fairly complicated).

3. I want icons for everything that is related to a quest to show on the map (bus stops, shops with opening hours, etc.) so that when I'm outside a shop and see that there are no questions, I can tell if it's actually on the map or not. I think this will help a lot in expert mode, when we can add custom notes.

The main reason I have added this PR here too, instead of waiting for tangram to accept the PRs is that I know that other StreetComplete users would be interested in seeing housenumbers and other labels on the map, and they can take this PR until such time as the upstream cinnabar style has updated.

Finally, if you are willing to accept this PR prior to any upstream acceptance from tangram, I, personally, am willing to take on any extra maintenance burden that will arise.

**Comment by westnordost** [comment]
> 1. 

Yes, that's fine.

> 2.

Yes, it would increase the maintenance as opposed to the way it is now (copying over releases of cinnabar without modification). But as said, maintaining modifications of cinnabar will be an annoying thing to maintain. I do not want to do that.

> 3.

We have a major difference there because I do explicitly **not** want that. I don't want icons that are not relevant or much less relevant than the quest icons to compete for the user's attention.

> Finally, if you are willing to accept this PR prior to any upstream acceptance from tangram, I, personally, am willing to take on any extra maintenance burden that will arise.

That is a fair offer, but you act on the assumption that they will merge your proposed changes. Also, you did change more here than upstream (point 2).

**Comment by westnordost** [comment]
Also, the next release will be in at least 2-3 weeks from now because 2.4 seems quite stable as it is. So there is really no reason to rush.

**Comment by dbdean** [comment]
The only change I made here, that I haven't sent to upstream, is the reference to `label-11.yaml` instead of `label-5.yaml`, which I *think* is how you are supposed to change themes in these styles. That's the subject of https://github.com/tangrams/cinnabar-style/issues/51, as I'd like cinnabar to make this a bit clearer.

I reckon we can convince mapzen/tangram to at least have one of their 'themes' that is suitable for us as a minor modification of cinnabar, at least until someone takes on the pokemon/tron map style work.

With respect to my point (3), how would you feel about the future 'export mode' having a more detailed map, but the normal mode having the simpler abstract map?

**Comment by dbdean** [comment]
Note that for my point 3, I am only saying that, ideally, unobtrusive POIs for *active* (when that is implemented) quests should show up, even if all questions are answered. This would allow a note to be dropped if I know I'm at a bus stop, but StreetComplete isn't asking me any bus-stop questions, and I can't see the bus-stop POI icon.

**Comment by westnordost** [comment]
> With respect to my point (3), how would you feel about the future 'expert mode' having a more detailed map, but the normal mode having the simpler abstract map?

That thought crossed my mind already, yes. The user could select a map style from a selection of several ones. Though, I am trying to have as little as possible settings around. Instead, decide based on a heuristic which elements on the map should best be shown.

The example you give with the bus stops is not really relevant (yet), because you cannot drop a note at an arbitrary location.  SC covers the use case of extending on previously surveyed area, not a first survey (adding nodes). Maybe some day it will, but until then, there is enough other stuff to do on its main purpose.

**Comment by westnordost** [comment]
@dbdean did you take note of https://github.com/ENT8R/streetcomplete-mapstyle ? The project looks very promising and will quite likely replace the cinnabar theme with that one if that project is successful. You are invited to push your improvements there. It is managed by another frequent contributor, @ENT8R 

Best of all, it's just 200 lines of code, so it is pretty easy to have an overview there.

**Comment by westnordost** [comment]
So, well, I will close this PR, but until a custom map style is found, there is no ETA, new cinnabar versions from upstream can always be merged.

**Pull request closed without merging**
