### PR TITLE
Standardized cases of changeset comments

### LINKED ISSUE #2001: Consistently start changeset comments with uppercase letters
I just noticed that the comments StreetComplete put into its changesets have the case of the first letter (often: "add") used inconsistently. See this screenshot from my OSM profile:

Change_sets

As changeset comments have the nature of headlines I'd suggest to convert the (probably few) comments with a lowercase first letter to uppercase (e.g. "**A**dd whether traffic signals have a button for pedestrians").

(SC 20.2 and 21.2 from F-Droid.)

The cycling cat

### PR DESCRIPTION
**Pull request by cyclingcat**
Yeah! My first pull request ever :-) Fixes #2001. As far as I searched through the source files it was just the two strings in the screenshot of above mentioned issue.

The cycling cat

(P. S.: Feel free to criticise me, if I did something wrong during the whole PR creation process.)

### CODE REVIEW

**Comment by westnordost** [comment]
Congrats! Will go through your PR in a moment

**Comment by westnordost** [comment]
Oh, that's it? I thought there would be more. Well, thank you!

**Comment by matkoniecz** [comment]
> Yeah! My first pull request ever :-)

Congratulations :)

**Comment by kmpoppe** [comment]
That was *totally* not what I was expecting 😅
I thought you were going to replace the first character of the commit message by an uppercase character before it gets uploaded, but oh well ... This will totally work of course!
Congrats on your first PR, we all came from there :)

**Pull request merged**
