### PR TITLE
Fix for #375: Only substitute the location's name in strings

### LINKED ISSUE #375: i18n: piecing words together to make a human-facing phrase is bad
For example, "Is this %s wheelchair accessible?" that would be used with "bus stop", "subway entrance" and "location". Many languages are gendered, and can have different forms of pronouns and even adjectives depending on a subject described. Let's take pronoun "this", in e.g. Spanish it will depend on gender of that thing that it points to: "este" for masculine and "esta" for feminine. Adjective "accessible" in Russian is also tricky like this: "доступен" and "доступна". So there's no way to translate this phrase so that it would always work correctly in those languages.

To be fair, I don't know if Spanish would be fine for now, because "parada", "entrada" and "ubicación" (if that's what the translators chose, I can't see it) are all feminine, but there's also no way to guarantee that all location types would be like that in the future. The fact is, in Russian this phrase already falls apart as it is now.

### PR DESCRIPTION
**Pull request by Teester**
This pull request fixes #375.

The only substitutions made now in the wheelchair quest are to add the location's name to the string, where that exists.

### CODE REVIEW

**Comment by westnordost** [comment]
"Is %s wheelchair accessible?" with "this bus station" etc. would be better

**Comment by antonv6** [comment]
I'd say it looks good to me right now. Complete phrases allow the most natural translation. Just would like to remind to check if `quest_wheelchairAccess_name_title` is used after the changes.

**Comment by westnordost** [comment]
Sooner or later, this project should use a (third-party) dictionary that translates any tag to a localized feature so that StreetComplete gains the ability to freely reference any element by name. 
See https://forum.openstreetmap.org/viewtopic.php?id=56889 for my deliberations. The project I was talking about sits on my hard drive still btw, if anyone would like to have a look.

**Comment by antonv6** [comment]
I don't think such a dictionary would include "this" in tag names, so it would make this problem reappear.

I guess if you want to name any element on the map, the name should appear as a separate UI element (to indicate the context) and be excluded from quest descriptions completely.

**Comment by westnordost** [comment]
It would need to include the pronoun, i.e. _parada, la_

**Comment by Teester** [comment]
Bear in mind that there are two separate phrases for each element:
- Is this bus station wheelchair accessible?
- Is the bus station “Central” wheelchair accessible?
So you would need separate strings for "this bus station" and "the bus station" etc

Initially, the wheelchair quests had a total of 10 strings to translate.  This pull request increases the total to 12.  using "this x" an "the x" as separate strings would require a total of 14 strings and potentially make if more difficult for translators to see the context of the phrase they are translating.

Another option is to change the phrases to:
- Is this bus station wheelchair accessible?
- Is this bus station “Central” wheelchair accessible?

@antonv6  `quest_wheelchairAccess_name_title` is still used in the wheelchair access quest for businesses.

**Comment by westnordost** [comment]
Hmm okay I see. Well then, I guess there is no way around there right now.

**Pull request merged**
