### PR TITLE
Remove date from image file name

### LINKED ISSUE #791: Privacy Issue: File Name of Uploaded Pictures Contains Date and Time
**Situation:** The filename of images uploaded by the application contains the exact date and time at which the picture was taken. Example: https://lut.im/tdaceZP1nK/3K9j5PNSaINt5cNu has as filename `photo_20180122_113718_-113362464.jpg`. This contains the exact time I took the picture.

**Comment:** The privacy issue here is that more or less detailed movement profiles could be constructed. Sure, when uploading to OpenStreetMap, the timestamp of this moment when the uploading took place is automatically included by the OpenStreetMap server. But users can wait some hours or days before uploading if they want to protect some of their location privacy.

**Suggestion:** I suggest to give the image a random filename. Date and time are not needed, and are anyway only included in the filename, which most people won't spot.

Please note that overall I am very happy about privacy: images do not contain any other metadata, and StreetComplete does apparently not include other timestamps in the uploaded data. Nice :) Keep up the good work, I enjoyed doing some quests today and will definitely continue to do so.

### PR DESCRIPTION
**Pull request by ENT8R**
This PR fixes #791.

### CODE REVIEW

**Comment by rugk** [comment]
But always giving the same filename may also not be suitable, is it?

**Comment by westnordost** [comment]
Won't work. This way, one photo will overwrite the other.

**Comment by westnordost** [comment]
Oh, nevermind. But please, test this once with 2 images attached to a note.

Comment here once you've done it and I'll merge it

**Comment by ENT8R** [comment]
> Won't work. This way, one photo will overwrite the other.

Are you sure? I don't believe that the `-113362464` prefix is always the same... But maybe I also understood the documentation wrong

**Comment by ENT8R** [comment]
> Oh, nevermind. But please, test this once with 2 images attached to a note.

Oops did not read that... I will do this!

**Comment by ENT8R** [comment]
I tested it now and it works!
First picture: https://lut.im/KOvDLkJNsP/AnpzMPGx4av4iFPX
Second picture: https://lut.im/Ve0n8CdLXs/YEJ09t3lte5xtPaI
Both were successfully uploaded and associated with the same note!
BTW: Does anybody of you use the OSM API testing servers sometimes? I just can't authenticate through OAuth if I use one of the testing servers... StreetComplete always says: "All permission need to be granted!". So I always have to use the normal website for testing which is not a good thing...

**Comment by westnordost** [comment]
Great, thanks!

No, never used it because I usually need real data to test.

Am 23. Januar 2018 16:19:24 MEZ schrieb ENT8R <notifications@github.com>:
>I tested it now and it works!
>First picture: https://lut.im/KOvDLkJNsP/AnpzMPGx4av4iFPX
>Second picture: https://lut.im/Ve0n8CdLXs/YEJ09t3lte5xtPaI
>Both were successfully uploaded and associated with the same note!
>BTW: Does anybody of you use the OSM API testing servers sometimes? I
>just can't authenticate through OAuth if I use one of the testing
>servers... StreetComplete always says: "All permission need to be
>granted!". So I always have to use the normal website for testing which
>is not a good thing...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/pull/793#issuecomment-359823003

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
> test this once with 2 images attached to a note.

Sounds like a good thing for the a unit test. 😄 

> So I always have to use the normal website for testing which is not a good thing...

Better open a new issue for that.

**Comment by ENT8R** [comment]
> Better open a new issue for that.

I don't think that this is related to StreetComplete... I think this has something to do with the testing servers (https://apis.dev.openstreetmap.org/)

**Pull request merged**
