### PR TITLE
raw-pt/abbreviations.yml: fix typo

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by matkoniecz** [comment]
Note https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

It is preferable to use POEditor and wait for regular merge by @westnordost (as it removes problem of conflicting changes on POEditor and from PRs)

**Comment by waldyrious** [comment]
Good point, that didn't occur to me. I was mostly following the steps of #1143.

That said, I believe these files, whose keys (not just the values) are language-specific, are not set up for translation in POEditor, and indeed I [can't find them there](https://poeditor.com/projects/po_edit?order=&filter=&id=97843&id_language=128&search=marcheal), but please correct me if I'm wrong.

**Comment by rugk** [comment]
AFAIK, yes, they do not exist in poeditor.

**Comment by matkoniecz** [comment]
In that case I am sorry for adding unnecessary confusion.

**Comment by waldyrious** [comment]
I don't think it was unnecessary. It probably represents a gap in the project documentation, e.g. more specific information in the translation instructions.

**Pull request merged**
