### PR TITLE
Change opening_hours clock to show 10:10

### PR DESCRIPTION
**Pull request by rugk**
Fixes https://github.com/westnordost/StreetComplete/issues/514

newclock

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
I thought #521 was already this fix...

**Comment by rugk** [comment]
https://github.com/westnordost/StreetComplete/pull/521 fixed another clock, for q quest, which does not exist yet. I noticed later that the clock was, of course, also used here. 😊

**Comment by westnordost** [comment]
I also thought it is. I made many changes to the file now. I will just change it like in the picture and close this PR.

**Comment by rugk** [comment]
Hu, okay, it was mergable, but I think you did not upload the changes (git could still have taken care of that, but…), anyway, does not matter.

**Pull request closed without merging**
