### PR TITLE
Add building name to quest title if it exists.

### PR DESCRIPTION
**Pull request by Binnette**
Hi, here is a simple fix to add building name (if it exists) in quest "housenumber" title.

Without my fix :
screenshot_20170711-105731

And with my fix :
screenshot_20170711-114554

### CODE REVIEW

**Comment by Binnette** [comment]
BTW, I merged "strings-fr.xml" cause it allows me to have latest translations in dev version.
Also, I allows to keep revisions of "strings.xml", cause PoEditor do not provide history (does it ?).

I hope you don't mind @westnordost :blush:

**Comment by westnordost** [comment]
I don't mind. However, I am not so sure where this makes sense. Certainly not for that KFC there.

In what situation would it be helpful to know the building name? I cannot think of any.

**Comment by HolgerJeromin** [comment]
Some churches and other pois are missing numbers, as the name of the poi hides the missing data. 
Showing the name would make the matching on site easier.

But for example the Aachen Dom got its housenumber because the internet provider (remote heating control) needed one for the contract. :-) so not every poi has a number.

**Comment by westnordost** [comment]
This comment is a bit off topic though. The PR is not about showing this quest if a poi has a name, but showing the name in the title of this quest.

Even if the name would be somehow helpful, wouldn't it make more sense to display it on the map rather than in the question for many different quests?

**Comment by Binnette** [comment]
> the name would be somehow helpful

I think it will. I was thinking about a very long and very thin street with many tiny shops. GPS is not very accurate (given weather, or nearby obstacles like tall buildings). So it can be helpful to have a confirmation in quest title, that i'm currently adding housenumber to the well corresponding shop.

> wouldn't it make more sense to display it on the map

Adding names on map is not a good idea, since the quest icon is gonna hide them.
Also I think that adding all names on map can be messy for a tiny render (smartphone).

**Comment by westnordost** [comment]
The building will not be named after the tiny shop in the ground floor. The building outline is only = the shop outline if the shop fills the whole building. This is especially not the case for those small shops - these are normally mapped as nodes.

**Pull request closed without merging**
