### PR TITLE
avoid asking of height on private roads

### PR DESCRIPTION
**Pull request by matkoniecz**
excludes access=no, vehicle=no, vehicle=private in addition to the current access=private

### CODE REVIEW

**Comment by westnordost** [comment]
but why?

**Comment by matkoniecz** [comment]
Because asking on private unsigned driveways is pointless (though it may be specific to my region that private driveways going through tunnel=building_passage are unsigned).

Adding access=no to access=private should be obvious.

**Comment by westnordost** [comment]
What about all those driveways in the (commercial) city center that lead to underground garages that are private in one way or another (rented spaces belonging to the companies that are situated in these building complexes) and thus are usually tagged that as `access=private`?

The point of all these "exclude private" clauses in most of the quests for ways is that the surveyor will likely not be able to get there to survey it. It's not in the query because "it makes no sense to map something private". Of course, mapping something private has very little information value for the general public but only because of that I would not just per se exclude it from everywhere.

**Comment by matkoniecz** [comment]
> What about all those driveways in the (commercial) city center that lead to underground garages that are private in one way or another

Should not excluded, see https://github.com/westnordost/StreetComplete/pull/1242/files#diff-101af1dce8d19c86115821d8bfe9d166R30

> Of course, mapping something private has very little information value for the general public but only because of that I would not just per se exclude it from everywhere.

Part of PR was done for this reason. Not only it is dubious for me whatever anybody would ever use this data but also all of them in my region are `below_default`.

But if you think that it should not be excluded - I will submit reduced version excluding just access=no and I will keep vehicle=private/no exclusion in my private fork.

**Comment by matkoniecz** [comment]
Though I tested it again - and something goes wrong for notes query.

**Comment by westnordost** [comment]
oh right, so the PR only improves the current query, I misread that.

**Comment by gdt** [comment]
private is funny, because it means "only if you have permission", but who has permission is hard to figure out, and having height when you do is just as useful as having the way be routable when your destination is in the private area.

So I think it comes down to being able to figure out the answer.

Maybe there should be a general filter about quests that ask about things in private areas, and be able to turn that on/off, or maybe only show them when distance is < 100m.

**Pull request merged**
