### PR TITLE
Add graphic for "Sixth Sense" achievement

### PR DESCRIPTION
**Pull request by FloEdelmann**
Follows #1993.

Used (and edited) images:

* Dog: https://openclipart.org/detail/284912/police-dog
* person, streetlights, zebra crossing, trees: StreetComplete achievement graphics by Sanja Dimitrijevic

Preview with achievement frame:

ic_achievement_blind

### CODE REVIEW

**Comment by westnordost** [comment]
Sanja wrote: "I love it! Looks great!". She also said that she wants to start again contributing more graphics within a month or two.

I have a few comments regarding this graphic:
- the graphic is a little empty in the center. All the detail is on the sides. Not exactly sure what to do about it. Maybe one solution would be to make the person with his dog bigger so that he sticks out to the upper right and move the traffic lights to the right, maybe also enlarging it a bit.
- when I last researched it, the the yellow band with three black dots is actually mostly or only used in Germany, the international symbol for blind people is basically a pedestrian with a blindman's stick. Maybe it could be made more clear that he is blind, because his blindman's stick is also not that well visible by giving him sunglasses... or something

**Comment by matkoniecz** [comment]
> yellow band with three black dots

On the first sign it seemed to be a radioactivity symbol.

**Comment by HolgerJeromin** [comment]
The stick should probably be white

**Comment by westnordost** [comment]
White stick on white zebra strip?

**Comment by smichel17** [comment]
Maybe this is just because I'm not familiar with the badge on the person's arm, but at that size it looks like :radioactive: to me

**Comment by peternewman** [comment]
> The stick should probably be white

> White stick on white zebra strip?

I assume your downvote was due to the lack of contrast @westnordost ? They're generally white:
https://en.wikipedia.org/wiki/White_cane
https://www.rnib.org.uk/cane-explained

The zebra crossing should have equal ratio of black and white, so the cane would be more obvious over a black bit of crossing, or perhaps it could have an outline, or one or the other be off white. See arguably the most famous zebra crossing in the world:
https://en.wikipedia.org/wiki/Abbey_Road,_London

**Comment by peternewman** [comment]
>     * the graphic is a little empty in the center. All the detail is on the sides. Not exactly sure what to do about it. Maybe one solution would be to make the person with his dog bigger so that he sticks out to the upper right and move the traffic lights to the right, maybe also enlarging it a bit.

If he walked the other way, the man could be much bigger in the middle of the frame, with the dog either within it or escaping the frame.

**Comment by michaelblyons** [comment]
> If he walked the other way, the man could be much bigger in the middle of the frame, with the dog either within it or escaping the frame.

Dropping the leash in favor of the special harness for guide dogs would bring the dog and person closer together, and they could both fit in the middle. (Also less ambiguity in the scene, since only blind people use those harnesses as far as I know.)

**Comment by peternewman** [comment]
> since only blind people use those harnesses as far as I know.)

It seems other types of service dog can too, but probably not many/any pets.

**Comment by westnordost** [comment]
A friend of mine will drew an icon for this, so this can be closed.

**Pull request closed without merging**
