### PR TITLE
make log more friendly to humans

### PR DESCRIPTION
**Pull request by matkoniecz**
avoid 'Hit Overpass quota. Waiting 1100000ms before continuing'

### CODE REVIEW

**Comment by westnordost** [comment]
🤖

**Comment by matkoniecz** [comment]
\*beeep\* \*beeep\* \*beeeeeep\*

**Comment by westnordost** [comment]
btw would you mind checking if I got everything right here for Poland?
https://wiki.openstreetmap.org/wiki/Default_speed_limits
Unfortunately, the source of this information is quite bad. All the other countries have as source a link to the section in the actual code of laws.

**Comment by matkoniecz** [comment]
@westnordost OK, I added it to my OSM TODO list - I will try to track down the rules in the legal act, rather than Wikipedia.

**Comment by rugk** [comment]
Well… if you find issues in the Wikipedia article, you may also correct them. Just saying… :wink:

**Comment by westnordost** [comment]
The wikipedia is sadly very incomplete on the topic of maximum speed limits. But TBH I have my hands full with OSM wiki stuff, soo... maybe some day the information I (/we) put together in the OSM wiki can be used as a source for wikipedia in return (since we also collect all the sources, so wikipedians can link "through" to the primary source)

**Comment by rugk** [comment]
Was rather speaking to @matkoniecz, but yeah… possibly even Wikidata may be the better place for it – totally depends. But let's not worry about this right now.

**Comment by matkoniecz** [comment]
@rugk I plan to add sources also to Wikipedia articles (if doable without rewriting entire articles).

**Pull request merged**
