### PR TITLE
+images for railway crossing quest

### PR DESCRIPTION
**Pull request by ServusWorld**
added the svg files for the new railway crossing quest

### CODE REVIEW

**Comment by rugk** [comment]
You have quite some empty space around them (they are in the top left corner). I guess this was accidential…

**Comment by ServusWorld** [comment]
oops that was not intended ... I've fixed that now

**Comment by goldfndr** [comment]
Could the foreground post maybe be lowered a bit? It would be more symmetrical with the background post wrt the road, and the gate wouldn't intersect with the rail (which, as a partially color blind person, makes it harder to see).

**Comment by rugk** [comment]
Just FYI you have some color filters in Android, AFAIK (in the developer settings).
Anyway, good idea, just need to be keept in a way so that the perspective does not look weird, i.e. the stuff still keeps it's perspective.

**Pull request merged**
