### PR TITLE
Add small issue template

### PR DESCRIPTION
**Pull request by rugk**
Only includes some explanatory text, but you could expand it to actually have fields for version numbers, etc.

### CODE REVIEW

**Comment by westnordost** [comment]
Ok, no idea what it does

**Comment by rugk** [comment]
Open a new issue and you'll see… I think then you get it.

If you want some proper info: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by westnordost** [comment]
Oh

Then, sorry, I do not like that. I don't like if the input is prefilled with stuff, that's not what an input field is for.

**Comment by rugk** [comment]
Okay, it's just so you can make issues much more useful then by forcing users to add needed details and explain things. It makes maintaining issues likely easier…

Usually you also prefill it like that:
```
## bug reports

StreetComplete version:

Android version:

Location:

blabla: 

```

**Pull request merged**
