### PR TITLE
Change POEditor URL to a working one

### PR DESCRIPTION
**Pull request by Etua**

### CODE REVIEW

**Comment by westnordost** [comment]
That is the URL to join the translation as a new contributor

**Comment by Etua** [comment]
Indeed, but I could not find anything else pointing to the whole project rather than a specific language and the old URL is dead.

**Comment by westnordost** [comment]
It's not dead, I can access it perfectly fine.

**Comment by Etua** [comment]
Don't you get an 404 error at https://poeditor.com/projects/view?id=97843 Could someone else check it on their device/account? Maybe that has to do something with your administrative rights because I could not load this page both as anonymous user and logged contributor.

**Comment by ENT8R** [comment]
> It's not dead, I can access it perfectly fine.

This is also what #629 is about. You can vote at https://poeditor.uservoice.com/forums/171919-general/suggestions/31242085-public-url-to-view-project-contributors or leave a comment for that topic. But it's a little bit strange that they didn't consider adding this for more than three years now even though the feature got nearly 100 votes...

**Comment by Etua** [comment]
@ENT8R Could you try opening this link right now? When I'm logged out of the website it prompts me to log in but opening it after that just returns:
Screenshot_2020-10-17 Error

**Comment by ENT8R** [comment]
Yes, that's what I see but also what I expected as the link https://poeditor.com/projects/view?id=97843 leads to a dashboard that only the owner of the project can see. There was an attempt to change or improve this behaviour so that everybody who is not the project owner can see the list of all contributors, but the team behind POEditor did not respond yet (see my last comment)

**Comment by Etua** [comment]
Then the original URL does not serve it's purpose and my thought was that entering the project is currently the closest you can be to a list of all contributors because you can manually check the attribution of every string. It's not ideal but still better than 404 to everyone without administrative rights.

**Comment by westnordost** [comment]
Hm, isn't there an url just to access the project as a language contributor?

Am 17. Oktober 2020 10:00:11 MESZ schrieb Dominik Danelski <notifications@github.com>:
>Then the original URL does not serve it's purpose and my thought was
>that entering the project is currently the closest you can be to a list
>of all contributors because you can manually check the attribution of
>every string. It's not ideal but still better than 404 to everyone
>without administrative rights. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/pull/2173#issuecomment-710769632

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ENT8R** [comment]
No, even their API (https://poeditor.com/docs/api#contributors_list) does not allow me to access the contributors of other projects using my API token, I can only see the contributors of my own POEditor projects...

**Comment by westnordost** [comment]
Hm well, I guess this is the best option then. Thank you!

**Pull request merged**
