### PR TITLE
give hint about repurposed buildings

### PR DESCRIPTION
**Pull request by matkoniecz**
implements part of #1913

"Can't say" menu would  have a new entry:

> Purpose changed over time</string>

with 

>Select the purpose defining the building. The question is about the current building form. It is not about its historical form, it is not about how building is used.
>
> Church building used as a warehouse is still a church building.
> Train station building that is now abandoned or housing a museum should be still marked as a train station.
> But rebuilding may erase original form, for example factory may be rebuilt so extensively that the current form is now a residential building.

shown

### CODE REVIEW

**Comment by matkoniecz** [comment]
ping @Helium314

**Comment by westnordost** [comment]
But `building` is tagged, so wouldn't that hint be wrong?

**Comment by matkoniecz** [comment]
> wrong?

Which part?

**Comment by westnordost** [comment]
> The question is about the current building form. It is not about its historical form

Right, I only read the first paragraph. The explanation is a bit long.

Anyway, I think I stated this before but I think the current uncertainty (in, that it is not explained) is better:
1. If the user has no doubt that a church used as an office building should be tagged as a church building, that's fine
2. If the user has no doubt that a church used as an office building should be tagged as an office building, that's still sort of fine because `building=office` is still an improvement from `building=yes`
3. If the user has doubt how to tag it, he can leave a note and explain it. This is actually the preferred way in such a case, because it allows that the building is tagged both for `building` and `building:use` correctly after discussion.

Offloading such a decision onto the user makes it more complex to him and at the same time does it not improve the situation, because he then might consider to tag it correctly as a church but the information that it is now used as an office is lost.

So this is why this hint should not be implemented.

**Comment by matkoniecz** [comment]
> building=office is still an improvement from building=yes

I think that it is not an improvement, as it is both incorrect and harder to spot and fix.

I was thinking also about case of confused user that wants more info, become more confused and quits instead of leaving notes. Not sure how common this is, but so far everything I have seen indicates that casual/newbie users are quite confused and unsure  

(warning about a small biased sample size, also it is possible that such people would be unlikely to become OSM mappers anyway - AFAIK noone continued mapping after app testing - both from initial user testing and also from later similar and even smaller tests).

**Comment by matkoniecz** [comment]
> So this is why this hint should not be implemented.

Can you review #1913? I liked at least some parts (for example about surface), but it would be probably more efficient to review ideas from it without making PRs for them.

**Comment by westnordost** [comment]
> Can you review #1913

I'll do that sooner or later. For now it's too much and there are enough other open things to do while at the same time I do not have much time for StreetComplete at the moment.

**Comment by matkoniecz** [comment]
> I'll do that sooner or later. 

Thanks! I will wait for that before making any new PRs based on ideas from it.

> I do not have much time for StreetComplete at the moment

So even bigger thanks for review of my PRs.

**Comment by peternewman** [comment]
> > The question is about the current building form. It is not about its historical form

Erm that's exactly what the tag is about @matkoniecz, from the top of the wiki page https://wiki.openstreetmap.org/wiki/Key:building :

> Note that it may be not the same as the building's current use (tagged using building:use=*). For example, a hospital building that is abandoned or repurposed to be a marketplace is still a building=hospital, and to mark active hospitals amenity=hospital is used.

> 
> Anyway, I think I stated this before but I think the current uncertainty (in, that it is not explained) is better:
> 
>     1. If the user has no doubt that a church used as an office building should be tagged as a church building, that's fine
> 
>     2. If the user has no doubt that a church used as an office building should be tagged as an office building, that's still sort of fine because `building=office` is still an improvement from `building=yes`

Surely that means we're getting it tagged with the wrong data and that makes it much harder for a more experienced mapper to be able to spot it's building=church and building:use=office, whereas if it's just yes they know it needs a survey.

>     3. If the user has doubt how to tag it, he can leave a note and explain it. This is actually the preferred way in such a case, because it allows that the building is tagged both for `building` and `building:use` correctly after discussion.
> 
> Offloading such a decision onto the user makes it more complex to him and at the same time does it not improve the situation, because he then might consider to tag it correctly as a church but the information that it is now used as an office is lost.
> 
> So this is why this hint should not be implemented.

:facepalm: Just realised you're saying the same thing as me.

Controversial suggestion, given building/building:use is a bit of a mess, would it be worth considering either de-prioritising the quest, or splitting it into two so it first asks you is this building still being used for the purpose it was made for, and then either tags building if yes, or asks you twice and tags both if not? While possibly adding the direct quest as a disabled by default option in the quest selection for experienced operators so they can avoid the additional question (and just manually tag/note the new usage somehow).

**Comment by westnordost** [comment]
The building quest is relatively high up because the housenumber quest depends on it. Splitting it in two quests would make the flow much longer for 99% of cases (while also not being possible anyway because there is no tag in OSM that signifies "building use is the same as building type").

So, I will close this PR as will not fix/merge. I agree that leaving a note always breaks the flow somewhat but I see no good way to handle this edge case without breaking the user's flow as per my last comment.

**Pull request closed without merging**
