### PR TITLE
Add description for multiple garages

### PR DESCRIPTION
**Pull request by smichel17**
For #1716

### CODE REVIEW

**Comment by westnordost** [comment]
Hm actually it was deliberate to not act on your suggestion, because I don't know how this additional information would be helpful to remove doubt.

**Comment by smichel17** [comment]
My problem was: "The garage in front of me has two doors and one roof. What should I mark it as?"

- It did not obviously fit the single garage picture because the single garage picture only has one entrance
- It did not obviously fit the multiple garages picture because the multiple garages picture has multiple roofs.

**Comment by westnordost** [comment]
But it is good that it does match neither, because in the case described, the user ought to use his judgement (or in doubt, open a note) to either sort this garage as a garage or as a garages: Some garages with 2 doors might correctly be tagged with garage, others with garages.

**Comment by smichel17** [comment]
> the user ought to use his judgement

That's reasonable, but the judgement should be about whether it fits the criteria for single or multiple, not what those criteria are (this is the job of the more-involved OSM community, or in cases where there is not consensus but you still want to offer the quest, yours).

In this case, it seems like the main criteria are having different owners/users/purposes, but those criteria are not mentioned in the quest, so users have to figure that out based on the name and icon.

> (or in doubt, open a note)

Maybe this is a personal problem, but I tend to skip quests where in doubt, rather than add a note.
Perhaps the UI could push me towards notes more, but that's a separate issue.

**Comment by westnordost** [comment]
Hmm, okay. After all, your addition is 1:1 what is in the wiki, so it should provide the necessary information. Will merge for the next major because it contains new strings.

**Pull request merged**
