### PR TITLE
Add icons for parking fee and parking access

### PR DESCRIPTION
**Pull request by ENT8R**
This PR adds two new icons for the parking fee and the parking access quest.
This is how they look:
image

P.S.: Could you tell me how you created those cool shadows for all the other icons? I just can't find the option...

### CODE REVIEW

**Comment by westnordost** [comment]
I'd drop a bit of the thin line detail on the downscaled icons (especially key) because these icons will usually be shown very much smaller than shown here.

To create the shadow, select all, copy it, paste the duplicate, ungroup all of the duplicate (ctrl+shift+g), select "Union" and then set the color to I think it was "#00000033"

**Comment by ENT8R** [comment]
Thank you for the hint! It works like a charm!
Is it better this way?
image

**Comment by westnordost** [comment]
Well...
* All shadows have the same y-offset: One box in the raster (I think it was 4px)
* The teeth on a 🔑 make it distinguishable
* the bill should be moved down (so it does not obscur the 🅿️) and sized up a bit.

**Comment by rugk** [comment]
> The teeth on a 🔑 is what makes it distinguishable, that's the last thing you should remove :-)

Right. currently looks like a pencil. 😆 Just noticed that.

**Comment by ENT8R** [comment]
> All shadows have the same y-offset: One box in the raster (I think it was 4px)

I just pressed the "down arrow key" to move it down... Is this the right way?

Now it looks like that:
parking_fee

**Comment by westnordost** [comment]
> I just pressed the "down arrow key" to move it down... Is this the right way?
AFAIK the down arrow key in Inkscape does not respect the grid.
I'll just make a few adjustments, okay?

**Comment by ENT8R** [comment]
Alright!

**Pull request merged**
