### PR TITLE
Add a Splash screen

### PR DESCRIPTION
**Pull request by ENT8R**
I created a simple splash screen for this app because the screen is just white when the app starts. With a splash screen the user can see that something happens in the background.
The splash screen automatically disappears if the MainActivity has loaded and shows only the primary color and the app icon. I hope you like it! :smirk:

### CODE REVIEW

**Comment by westnordost** [comment]
Thank you, ENT8R!

However, before merging your PR I first want to investigate why the startup became to take so long in the first place. Perhaps a start screen is not necessary after all.

**Comment by ENT8R** [comment]
This is totally okay. I hope you can fix the issue!

**Comment by westnordost** [comment]
See also #416

**Comment by westnordost** [comment]
The issue is fixed, startup is fast again.

**Comment by ENT8R** [comment]
Okay, I'll close this PR!

**Pull request closed without merging**
