### PR TITLE
avoid producing quests for access=no ways

### PR DESCRIPTION
**Pull request by matkoniecz**
access=no has over 300k usages (roughly 10% of acccess=private)
even stronger access restriction than access=private or synonymous

see #511 that requested support for access=private

### CODE REVIEW

**Comment by westnordost** [comment]
It's not as easy as that. Usually, `access=no` is paired with other access restrictions, such as `foot=yes` etc.
Also, almost half of all `access=no` streets are service roads. Most (of these) quests do not apply to service roads.

**Comment by matkoniecz** [comment]
> Usually, access=no is paired with other access restrictions, such as foot=yes etc.

In my experience (limited to what I edit and tag) access=private is coupled even more often with such access restrictions.

But from looking at taginfo, foot=yes is the most popularly combined with access=no/private. 

14% access=no has foot=yes, 1% of access=private has foot=yes.

9%, 0,7% respectively for bicycle=yes.

-----

I still think that it is desirable to avoid unsolvable quests, but I admit that it is not as obvious as I thought.

**Comment by westnordost** [comment]
Of course it is desirable, the overpass query just needs to be refined.

Apparently for `access=private` as well.

**Comment by matkoniecz** [comment]
So you would be OK with more complicated query, with something like

> (access != private and access != no) or (foot != private and foot != no)

query is quite ugly, but nothing really complicated: http://overpass-turbo.eu/s/rjk

**Comment by westnordost** [comment]
Shorter: `(access !~ private|no or foot !~ private|no)`

**Comment by westnordost** [comment]
So, are you going to finish it?

**Comment by matkoniecz** [comment]
Yes

**Comment by matkoniecz** [comment]
Is everything OK with filtering in changed quests?

Note - I noticed that there is still add road name quest to be changed. 

It has trickier construction of query, so I prefer to finish simpler quests as the first step.

---

BTW, do you prefer squashing & rebase or keeping multiple commits?

**Comment by westnordost** [comment]
Looks good. I usually squash.

**Pull request merged**
