### PR TITLE
Bicycle parking type

### LINKED ISSUE #330: Ask for bicycle_parking=*
My current idea is

What is the bicycle parking type?
- Stand against which you can lean your entire bicycle. Makes it possible to lock the frame and a wheel to it [bicycle_parking=stand]
- Secures only the front wheel (or possibly back wheel) [bicycle_parking=wall_loops]
- ? [bicycle_parking=rack] I have no idea what is the real difference compared to bicycle=stand
-  custom-built closed shed in which many bikes can be stored, possibly with individual stands inside. [bicycle_parking=shed]
- A special kind of bollard designed for bike locking. Generally, the bike is locked to the central pole and "arms" of some sort prevent thieves from simply lifting the bike over the pole. [bicycle_parking=bollard]
- Parking takes the form of lockers which enclose bicycles fully and individually, typically secured with some form of key or combination system. [bicycle_parking=lockers]

These answers cover more than 95% of bicycle parking types https://taginfo.openstreetmap.org/keys/bicycle_parking#values

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #330

Note, that is not mergeable - only xxhdpi drawable are added and authors are not documented.

But given that it is possible that images will be changed again I prefer to do both once at end once images are stabilized.

screenshot_2018-02-28-15-35-27-575_de westnordost streetcomplete debug

I am not 100% happy about any image but after next round of image searching, playing with saturation, recropping and other bikeshedding I am sending this as I think that it should be good enough (I am obviously willing to make changes if something is bad).

### CODE REVIEW

**Comment by matkoniecz** [comment]
@westnordost I attempted to play with saturation, contrast etc to improve the stand image - is it good enough? I asking as I am most likely to be biased here.

**Comment by rugk** [comment]
You may add "Fixes ..." in the PR description.

**Comment by westnordost** [comment]
Looks good 👍

**Comment by matkoniecz** [comment]
I added scaled images (I really need to make a script for that, manually rescaling in Gimp and copy-pasting it to proper folders is a poor method) and documented sources. It is now ready for merging.

**Comment by westnordost** [comment]
There is a plugin for Android Studio. I think it's called Batch Drawable Importer

On 1 March 2018 07:13:14 CET, Mateusz Konieczny <notifications@github.com> wrote:
>I added scaled images (I really need to make a script for that,
>manually rescaling in Gimp and copy-pasting it to proper folders is a
>poor method) and documented sources. It is now ready for merging.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/pull/923#issuecomment-369485122

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
I found this one - unfortunately it is not working for me and it is no longer maintained ( https://github.com/winterDroid/android-drawable-importer-intellij-plugin/issues/153 )

**Comment by rugk** [comment]
Just add these images as another element selection and tag as stands, anyway.

**Comment by matkoniecz** [comment]
Note https://github.com/westnordost/StreetComplete/issues/330#issuecomment-311511732

**Comment by matkoniecz** [comment]
Also, explanation of difference between stands and wheelbenders may be put into "can't" say menu - like proposed for addresses in #917 (I already planned it as a future enhancement).

**Comment by ENT8R** [comment]
> I really need to make a script for that, manually rescaling in Gimp and copy-pasting it to proper folders is a poor method

I did this for all answers for the new building quest (#774) 😄 Such a script would be a **really big** help!

**Comment by westnordost** [comment]
So, the plugin I use is called "Android Drawable Importer"

**Comment by matkoniecz** [comment]
> Nothing to complain. Will be merged for v5. :-)

I am curious - is there some reason why merging in future is better than merging now? Are we in a feature freeze for 4.0?

**Comment by matkoniecz** [comment]
And thanks for a review!

**Comment by westnordost** [comment]
Yes. Feature freeze starts with the first beta of any major release. Any update that I make on this version will only be bugfixes or very minor things. Only when that version is stabilized an no major or minor things pop up anymore, I will continue work on the next major version. This is why it took me so long to review the building type quest.

**Comment by xotgucuni** [comment]
@westnordost Sorry if spam, but do you have any response to my comments above? I think I was shadowbanned when I posted them, so they were hidden at first.

**Comment by matkoniecz** [comment]
> I think I was shadowbanned when I posted them, so they were hidden at first.

These replies were shown to me and as far as I know Github has no shadow bans.

**Comment by westnordost** [comment]
@xotgucuni did you read through the discussion at #330? 
Basically, the definition of racks is really unclear (i.e. search for bicycle rack on image search) and may be an umbrella term for all kinds of bicycle parking types. I umderstand it to be like wheelbenders but with a better design that is more secure and doesn't bend the wheels? The problem here is that there is no "typical" rack then, so adding this will rather add to confusion rather than otherwise. Additionally, if my above assumption is correct, there is really not any information value added as opposed to simply tagging as stands. In short:
1. bad definition in wiki might have burnt this tag. At least it needs to be clarified.
2. A typical picture would need to be found
3. Probably no meaningful difference to stands

Bollards are not in there because basically this is one of the many different possible stand designs. In terms of security, it is the same as stands, and this is what matters. I.e wide_stands are also not included.

**Comment by xotgucuni** [comment]
@matkoniecz Getting off-topic, but my account was flagged when I created it, and I had to contact support to resolve this. Before that, I had noticed that my comments were hidden if I was logged out.

@westnordost Thanks, makes sense.

**Pull request merged**
