### PR TITLE
make star icon clickable

### PR DESCRIPTION
**Pull request by matkoniecz**
2 out of 7 users during UX tests tried to click it, as their very first action
it is also quite obvious place to click
this adds some minimal info there, in future it may be place to show multiple badges/achievements

-----

My work on this pull request and UX testing was sponsored by a NGI Zero Discovery [grant](https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/368849)

### CODE REVIEW

**Comment by rugk** [comment]
So what happens when you click on it?

**Comment by matkoniecz** [comment]
Have you tried looking at the patch (see "Files changed" tab at top, linked to https://github.com/westnordost/StreetComplete/pull/1478/files )?

**Comment by rugk** [comment]
Just wanted to say this is a good info in a PR.

**Comment by matkoniecz** [comment]
> this adds some minimal info there

**Comment by goldfndr** [comment]
```xml
- <string name="about_missing_stars">Currently star count is not shared across devices, but answers are added directly to the OpenStreetMap database.</string>
- <string name="how_to_get_stars">Select one of markers on the map and answer the question. This way you will improve OpenStreetMap data and get stars. If you see no markers you may need to zoom out map.</string>
+ <string name="about_missing_stars">Currently, the star count is not shared across devices, but answers are added directly to the OpenStreetMap database.</string>
+ <string name="how_to_get_stars">Choose one of the markers on the map and answer the question. This way you will improve OpenStreetMap data and get stars. If you see no markers you may need to zoom in or out the map.</string>
```

I changed to "zoom in or out" because when one zooms out very far the markers disappear. I changed "Select" to "Choose", as the latter is a more fitting common term in the UI (UX?) when one doesn't have simultaneous multiple choice ability and the element interaction has an immediate consequence.

Normally, I prefer a "then" in such a long "if", but dropping it in informal conversation is common.

**Comment by rugk** [comment]
@goldfndr If you want your diff to be directly apply-able (on GitHub) you need to incooperate that in a comment on a _single line_ in a GitHub [review](https://help.github.com/en/articles/reviewing-changes-in-pull-requests).

**Comment by westnordost** [comment]
> on a single line

Which is not possible for a multi-line diff, or is it?

**Comment by westnordost** [comment]
Anyway, regarding this PR, I am not sure about this. I have other plans for the star button, namely, to lead to the stats and achievements screen later on. So, this feels like an intermediate solution to me, and I generally am hesitant to push intermediate solutions to be translated.

On the other hand, if the strings are written in a way that they fit later for maybe the "achievements" (= "did you know"-screens with nice pictures, triggered when reaching certain goals), it would not hurt.

**Comment by goldfndr** [comment]
I created a comment, using [gitlab syntax](https://github.com/isaacs/github/issues/1452#issuecomment-495892763), and now realize the syntax is GitLab's not GitHub's. :blush:

**Comment by matkoniecz** [comment]
> I have other plans for the star button, namely, to lead to the stats and achievements screen later on.

Yes, it was discussed a bit in #178 - I like this plan, this is intended as the first step in this direction.

> On the other hand, if the strings are written in a way that they fit later for maybe the "achievements" (= "did you know"-screens with nice pictures, triggered when reaching certain goals), it would not hurt.

My plan is to use both

> Select one of markers on the map and answer the question. This way you will improve OpenStreetMap data and get stars. If you see no markers you may need to zoom out map.

and

> Your answers are directly improving OpenStreetMap. Contributed data is open, everyone can use it. Many great projects are already using it.

in one of rewards/badges in a proper star menu.

> Currently star count is not shared across devices, but answers are added directly to the OpenStreetMap database.

is intentionally separate and merged manually into one string as hopefully in the future it will be no longer true (given results of UX testing I will try to work on stars/rewards/synchronization).

**Comment by matkoniecz** [comment]
@goldfndr 

Thanks for language review! I applied most of it

> I changed to "zoom in or out" because when one zooms out very far the markers disappear.

I decided to not use this part. For heavy zoom out there either is (or should be) some warning about this situation and warning that quest are hidden. And among new mappers is not something that seems to happen (though my sample size is low) and "zoom in or out" is making this advice really, really unclear.

**Comment by matkoniecz** [comment]
@westnordost At some point it got removed - is it a regression or an intentional change?

**Comment by westnordost** [comment]
Intentional. The tutorial replaced ths.

**Comment by FloEdelmann** [comment]
I still regularly try to click on the star to get to the profile

**Pull request merged**
