### PR TITLE
Solve or create note with image

### PR DESCRIPTION
**Pull request by ENT8R**
This PR adds a the possibility to upload an image if the user leaves a note or takes part in a note discussion. The image will be uploaded to https://lut.im after the user selected an image from the gallery. No credentials or a login is needed. If the image was uploaded successfully, a link to the image is displayed in the note input textbox, so that other users can easily access this image and hopefully solve the note. This feature was requested by many users in #90. I hope you like it 😄 

### Leave a note instead of answering a quest:

P.S.: I'm probably not online in the next week, so you don't have to wonder why I'm not responding to your questions and ideas 😉

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
That's a pretty neat service! Is it worth adding https://lut.im/about into the About Streetcomplete -> Credits UI as well?

**Comment by Binnette** [comment]
Does it lunch the camera or just open file explorer ? Camera would be great  !!!
I gonna test it this evening ! ☺

**Comment by ENT8R** [comment]
> Does it launch the camera or just open file explorer?

If you click at the button, the file explorer opens and you can select an image. I think, this is better than launching the camera, because if the user wants to work offline or save mobile data, he can take a picture while he's outside and upload it when he's at home and connected to his network.

**Comment by callis** [comment]
Another option: open camera, take pic, save completed quest, upload later (wifi)

**Comment by ENT8R** [comment]
Mmhh... But I think this is quite hard to implement...

**Comment by westnordost** [comment]
This is how it should work:

1. The leave note dialog has a button "Attach photo" (or as icon), clicking it will open the default camera app to take a photo (so this app does not need any additional privileges)
2. When returning from the camera app with the picture, it is shown below the text area that an photo has been attached, ideally the picture's thumbnail is shown there as well.  The user can repeat these steps any number of times to attach multiple photos.
The photos are NOT uploaded anywhere immediately but associated with the note and stored in local storage 
3. When the note is then finally uploaded, then as part of each individual note upload (so: in background), the photos associated with each of the notes are first uploaded to that image hosting service, then a text like "Attached photo(s):\n image url 1\n image url 2 \n etc.." is appended to the note text.

Yes, this is some work and you need to concern yourself with the database / persistent storage and where/how note quests are being uploaded but then it'll be a great feature and it will no problem work offline just like the rest of the quest solving.

Let me know if you have questions. To jump ahead, the upload is triggered through QuestController, there you can see to which class(es) it delegates the actual work to.

**Comment by westnordost** [comment]
Furthermore, there are some methodic quality issues with your code. Rather than commenting this everywhere in the changeset, I'll just make some general comments here since you need to restructure the code there anyway given my last comment. I hope this also helps you to improve in your profession in general:
* lots of duplicate code, this is not acceptable and I shouldn't need to tell you this in a code review. No further comment necessary I hope.
* spaghetti code: Avoid comments like in line 307, 321 etc of first file, instead put things that form logical units into own methods (or even classes, see below)
* one class, one responsibility: Your image upload helper does several things, try to separate this into own classes. This enables testability and reusability of the code and improves readability and then of course its maintainability. Most notably, it concerns itself with both UI and the "real" work. (jumping ahead, I'd say this is the main reason for the clumsy exception handling) But also, it constructs a multi-part form data by hand (perhaps write a class that facilitates this?) and reads a stream into a string in 20+ lines of code (there must be a staple solution for this and if not, perhaps move this into a static utility class function). Now, because of my last comment, this class neither needs UI nor being an async task anymore (because the quest upload already happens in a separate background thread) which should facilitate this a lot.
* exception handling: e.printStackTrace() is no proper exception handling. Generally you need to distinguish between two exception types: Exceptions that will be the programmers error if they occur at all (i.e. line 224) and errors that must be expected because they depend on something external (i.e. lut.im returns a 5xx http error code, the connection cannot be established etc). 
For the former, it is OK to simply wrap it into a RuntimeException and rethrow (if it isn't a Runtimeexception yet) because it "should never happen" and if it does, it is a programming error.
For the latter it must be handled properly: If it isn't recoverable (probably not in this case ), then any kind of error during the image uploading process should escalate (perhaps wrap it into an own exception) so the upload of the entire note fails.

**Comment by ENT8R** [comment]
Thank you for your feedback! I will close this PR and think about implementing this feature. I will tell you if I will do it or not!

**Comment by westnordost** [comment]
Ok

**Pull request closed without merging**
