### PR TITLE
Add new quest to determine the tracktype

### LINKED ISSUE #487: New quest: tracktype for smaller tracks/ways
In https://github.com/westnordost/StreetComplete/issues/38 @westnordost said:
> At least […]track type[…][ is on my list.]

:+1: for [tracktype](https://wiki.openstreetmap.org/wiki/Key:tracktype). It is as far as I see only useful for smaller tracks or paths, so reasonable as it is not asked for bigger streets or footpaths or so.
Mostly useful in forests when wandering.

I thought it is a good idea to open a new issue for that thing, as https://github.com/westnordost/StreetComplete/issues/38 is more or less a "meta issue".

### PR DESCRIPTION
**Pull request by ENT8R**
This PR adds a new quest for determining the [surface quality](https://wiki.openstreetmap.org/wiki/Key:tracktype) of a track. It fixes #487.

### CODE REVIEW

**Comment by westnordost** [comment]
Actually, I made an icon specifically for that, it's the tractor.

**Review by westnordost — CHANGES_REQUESTED** [review]
A few points:
1. Whoa, how did you scale those, with MSPaint? Looking especially at tracktype 2,3 and 4 it really does not look so pleasant
2. On the pictures, the very much most important part of this quest:
- track1 shows too much sky and too little of the track. I cannot really identify the surface
- track2 looks kind of less smooth than 3, where should be the tangible difference between these?
- track4 is bad, it should have the same appearance (minus the track) than the other pictures, not this red-brownish heathlands

**Comment by rugk** [comment]
> Actually, I made an icon specifically for that, it's the tractor.

Uhh? I actually correlate this icon used here much more with "track/way surface" than a tractor. A tractor may be about agriculture, so a quest about plants on a field or whatever. (I know, not a quest we want.)

And if you considered to use the tractor for that, what did you want to do with this icon?

**Comment by ENT8R** [comment]
> Whoa, how did you scale those, with MSPaint?

This was my tool/website which did this 😄 I fear this needs some adjustment...

> Actually, I made an icon specifically for that, it's the tractor.

I also thought that this icon would fit a little bit better...

Regarding the images: I will look for some better ones that will fit your proposals.

**Comment by westnordost** [comment]
> And if you considered to use the tractor for that, what did you want to do with this icon?

#279

**Comment by ENT8R** [comment]
Mmh... Alright. I find this still a little bit confusing.

**Comment by rugk** [comment]
Mhh ok. Considering the asked question, maybe the icon should try to represent _quality_ somehow? Some +/- signs, :+1:/:-1: or so (in a simplified way) or so on a street, maybe?

**Comment by goldfndr** [comment]
Rather than *quality*, I suggest *firmness*.

**Comment by ENT8R** [comment]
> track2 looks kind of less smooth than 3, where should be the tangible difference between these?

Maybe this is just because of the bad quality of the images, but I think grade2 is something like gravel and grade3 is sand or something softer...

**Comment by ENT8R** [comment]
> track1 shows too much sky and too little of the track. I cannot really identify the surface

maybe this one is better?
https://wiki.openstreetmap.org/wiki/File:Cesta_od_Le%C5%A1tiny_do_Lipnice_nad_S%C3%A1zavou_(2).jpg

**Comment by rugk** [comment]
Maybe it would be better if it had been photographed from an even lower position (i.e. frog perspective, but not looking up, but just straight on the road). Then you can also see more details of the surface itself.

BTW I also just noticed the question is a bit odd. "What is the quality?" -> "Soft".
An answer for the quality would be "Good" or "bad" or so. I would not expect "soft" as an answer. Maybe change the question to "What is the stability?", or, as it has been suggested "...firmness". Yeah, maybe firmness is the best.

**Comment by westnordost** [comment]
It would be ideal to have the different photos more or less show the same scene and in the same perspective but only have the track types differ. If on one photo, there is a forest but on the others, there are just meadows and shrubbery, people might be confused that this photo should be selected for tracks in a forest.

**Comment by ENT8R** [comment]
I changed the icon to the tractor now because the ways are mainly used by them. So it makes kinda sense to show it...
I also changed some images and rescaled all of them, so I would thinkt that this PR is ready for another review...

**Comment by rugk** [comment]
> because the ways are mainly used by them.

Only the bad ones, i.e. the ones with the bad quality. As this quest also can be answered with good quality/asks about the type in general, this argument makes no sense.

**Comment by ENT8R** [comment]
Well but for example the ways are allowed for (in German) "Land- und Forstwirtschaftliche Fahrzeuge" which implicites tractors... And I know also some tracks with a good surface quality like asphalt which can be used by tractors... I don't know which icon is the better one...

**Comment by westnordost** [comment]
Here would be some more pictures that might fit: https://github.com/westnordost/StreetComplete/issues/133#issuecomment-390477272

**Comment by ENT8R** [comment]
I replaced the images of grade1, grade2 and grade4 with some of the images made by @BjornRasmussen in https://github.com/westnordost/StreetComplete/issues/133#issuecomment-393650654
At least for me the difference between all of them is now pretty clear.
If you want to you can share your opinion!

**Comment by BjornRasmussen** [comment]
Nice use of the images!

**Comment by ENT8R** [comment]
> Nice use of the images!

I'm not really sure if you released all images under the under the CC BY 4.0 license or only the images used for the path surface quest... Because I only found [this comment](https://github.com/westnordost/StreetComplete/issues/133#issuecomment-393650654) where you stated that 6 images can be used but 2 of the images I used were mentioned earlier above and not in that comment. Would it be possible that you maybe release https://drive.google.com/file/d/1VzhiJin8IUIMFnQzOLeyDurttyeVPnbuXA/view and https://drive.google.com/file/d/1RJn5CW_AijVCWWtQ_cKHXmGFksTZ2ua9SQ/view under the same license too?

**Comment by BjornRasmussen** [comment]
Sure.
I release the following images into the pubic domain:
https://drive.google.com/file/d/1VzhiJin8IUIMFnQzOLeyDurttyeVPnbuXA/view
https://drive.google.com/file/d/1RJn5CW_AijVCWWtQ_cKHXmGFksTZ2ua9SQ/view

**Comment by westnordost** [comment]
The pics are really good now!

**Review by westnordost — APPROVED** [review]

**Comment by rugk** [comment]
Maybe you can exclude tracks already tagged with "surface=asphalt" (if that is a thing/happens for "highway=track"), as there the track type value is quite obvious, it's level 1 and one would not need to ask a surveyor about that.

As for the images, yes, they show what we want, but what catches my eye first are actually the differences between the images regarding whether there are trees at the left/right.

**Comment by ftrebien** [comment]
> Sure.
> I release the following images into the pubic domain:
> https://drive.google.com/file/d/1VzhiJin8IUIMFnQzOLeyDurttyeVPnbuXA/view
> https://drive.google.com/file/d/1RJn5CW_AijVCWWtQ_cKHXmGFksTZ2ua9SQ/view

Hi, sorry for reviving this old thread. It would be interesting to add these images to Wikimedia Commons for use in OSM's documentation. The links are no longer working; do you happen to still have the original high-definition images?

**Comment by BjornRasmussen** [comment]
> > Sure.
> > I release the following images into the pubic domain:
> > https://drive.google.com/file/d/1VzhiJin8IUIMFnQzOLeyDurttyeVPnbuXA/view
> > https://drive.google.com/file/d/1RJn5CW_AijVCWWtQ_cKHXmGFksTZ2ua9SQ/view
> 
> Hi, sorry for reviving this old thread. It would be interesting to add these images to Wikimedia Commons for use in OSM's documentation. The links are no longer working; do you happen to still have the original high-definition images?

I’ll look for them.

**Comment by BjornRasmussen** [comment]
I couldn't find the original source files, but they are still on Google Maps.  I also release these versions into the public domain.

Paved:
https://www.google.com/maps/@35.9320717,-79.0342743,3a,75y,267h,89.29t/data=!3m7!1e1!3m5!1sCIHM0ogKEICAgID4zdq8Cw!2e10!6shttps:%2F%2Flh3.googleusercontent.com%2Fgpms-cs-s%2FABJJf52Ze9FbsG_n2uD39P4kto5f5rct38zyckmos15TGJ5fboVpkziHOYPDvjHHGb9Ad4BJ1gIl1e4jcN-leEzKXIuQanRJhH0nw6KXL0Xf_WxhDxMc1NJBJXpsM7UJVSOY0h8t1BpI%3Dw900-h600-k-no-pi0.7147707554279634-ya352.6661630299431-ro0-fo100!7i6144!8i3072?entry=ttu&g_ep=EgoyMDI2MDUwMi4wIKXMDSoASAFQAw%3D%3D

Compacted:
https://www.google.com/maps/@35.937617,-79.0801618,3a,82.6y,193.58h,87.02t/data=!3m8!1e1!3m6!1sCIHM0ogKEICAgID4zdq8cw!2e10!3e11!6shttps:%2F%2Flh3.googleusercontent.com%2Fgpms-cs-s%2FABJJf503_juo48C_eOAUikshJOlDCOLkzMcOOTOnfFb87ooU5bbVZRZvRRvLByH9gjqwzmlEhEQ18HLJlBirm0dze6SRX0OW9rR_1dNuDAydRzdVlRZlBYIPcVIC3SAf4EiBMKmdooc%3Dw900-h600-k-no-pi2.976367147319138-ya355.58023490112146-ro0-fo100!7i6144!8i3072?entry=ttu&g_ep=EgoyMDI2MDUwMi4wIKXMDSoASAFQAw%3D%3D

**Comment by ftrebien** [comment]
@BjornRasmussen: Thank you! Unfortunately, Google Maps doesn't provide a way to attach a license statement to the photos, and due to Wikimedia Commons' licensing requirements, I would need a clear link between your Google account and your GitHub account in order to upload them legally. Would you mind uploading the images directly to Wikimedia Commons? That ensures everything is properly attributed and legally usable. Sorry for the extra work.

**Pull request merged**
