### PR TITLE
ask whatever laundry is self service

### LINKED ISSUE #1385: Add whether shop=laundry is a self-service laundry
### General
Affected tag(s) to be modified/added: [self_service](https://wiki.openstreetmap.org/wiki/Key:self_service)
Question asked: **Is this a self-service laundry?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary: Coin-operated washing-machines can usually be seen from the outside
- [?] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort): Either taginfo is broken, or almost no laundry shops have self_service tagged right now

### Implementation
A yes-no quest or like the car-wash quest if there should be more options.

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #1385

@westnordost Are you maybe planning icon for this quest? I can try finding/making one but your is going to be much better :)

### CODE REVIEW

**Comment by westnordost** [comment]
I don't expect that there are two laundries right next to each other, so I'd prefer if there was only one string to translate. (The one without the name.)

**Comment by westnordost** [comment]
Added a laundry icon

**Comment by matkoniecz** [comment]
> I don't expect that there are two laundries right next to each other

I was thinking about a bit different use case.

In case of place that is tagged as `shop=laundry` and is now say a restaurant, user may answer to

> Is this a self-service laundry?

"no", as in "this is not a laundry".

But maybe it is still not worth translating two strings?

**Comment by westnordost** [comment]
The wording could be "is this laundry a self service laundry"

**Comment by matkoniecz** [comment]
Thanks for the icon! I also applied suggested phrasing.

**Comment by westnordost** [comment]
Looks good, thanks!

**Pull request merged**
