### PR TITLE
Don't show the bus stop quests for NAPTAN hail and ride stop either

### PR DESCRIPTION
**Pull request by peternewman**
As mentioned in https://github.com/westnordost/StreetComplete/issues/1784#issuecomment-617146743
> Thanks, I think also `naptan:BusStopType != HAR` as some seem to have that but not physically present = no.

More work on #1784 .

I haven't compiled and tested this, but given it's a pretty trivial test...

### CODE REVIEW

**Comment by peternewman** [comment]
Test cases: https://overpass-turbo.eu/s/TkJ

**Comment by westnordost** [comment]
Hm, okay

**Comment by peternewman** [comment]
Thanks, probably a bit of an edge case, but avoids someone just opening the same thing for slightly different tagging in future.

**Comment by matkoniecz** [comment]
What is the meaning of this tag? 

I found https://wiki.openstreetmap.org/wiki/NaPTAN/Tag_mappings with "Hail and ride section of route," but it seems unrelated to bus stops. Or is it a small scale tagging for renderer? ( https://taginfo.openstreetmap.org/tags/naptan%3ABusStopType=HAR has just 100 of them )

**Comment by peternewman** [comment]
> What is the meaning of this tag?

https://en.wikipedia.org/wiki/Hail_and_ride

> I found https://wiki.openstreetmap.org/wiki/NaPTAN/Tag_mappings with "Hail and ride section of route," but it seems unrelated to bus stops. Or is it a small scale tagging for renderer and tagging of nonexisting bus stops? ( https://taginfo.openstreetmap.org/tags/naptan%3ABusStopType=HAR has just 100 of them )

I don't know the specific reason they ended up in OSM, I guess from the NaPTAN import, and I think I read something somewhere that they are to help the bus route take the correct route effectively (I guess for the renderer). When I looked it seemed it would be possible to do it with attributes for the relationship, but that isn't how they're currently tagged.

Anyway they exist on the map, but not in the real world, so we need to filter them out so SC doesn't spam questions that can't be answered.

**Pull request merged**
