### PR TITLE
Adding Office to building white list for building levels

### PR DESCRIPTION
**Pull request by HolgerJeromin**
http://wiki.openstreetmap.org/wiki/Tag:building%3Doffice

Status is in use. At least vespucci and josm (share Presets) suggests this tag.

### CODE REVIEW

**Comment by westnordost** [comment]
Hmm, building=office is deprecated

**Comment by HolgerJeromin** [comment]
You are probably right. 
But your list is a filter for catching normal multi level buildings. So merging this would allow 63000 buildings to set building:levels

**Comment by westnordost** [comment]
I am hoping that StreetComplete also has an effect as a catalyst to help reduce obsolete tags (by effectively ignoring obsolete tags). The question is, what is more important: covering as much data as possible or acting as a catalyst.
What is your opinion?

**Comment by HolgerJeromin** [comment]
Ok, that is a good point. Probably a new quest or maproulette.
building=office to
building=commercial,office=company or
building=public,office=government

**Pull request closed without merging**
