### PR TITLE
Bottom sheet redesign [Looking for Feedback]

### PR DESCRIPTION
**Pull request by westnordost**
* speech bubbles to emphasize the question-answer-style of this app
* tried to be a bit more "light", with non-bold question title and white background, see-through to the map areas at the sides

The redesign is a little more space-wasting. Screenshots are made on a 4,3" phone, which is about the smallest dimension that is still seriously supported.
The maxspeed-quest is the quest with the busiest UI to date.

What do you think? I am looking for feedback.

### CODE REVIEW

**Comment by westnordost** [comment]
Hmm, in direct comparison 


I am not sure myself if the bubble-type is better. By having the transparent areas at the side, the layout actually seems more busy.

**Comment by rugk** [comment]
Uh, nice! Personally, from the first view I'd say I like it. (A refreshing thing at least for the SC design.)

StreetComplete ie getting a chat bot. 😜 (just kidding, but kinda looks like it)

What I'd say would really matter in this design are the animations/transistions, how quests are shown etc. Because with chat bubbles, users assume a kind of animation they know from messengers etc. (see e.g. the advertisement videos for messengers, were these bubbles plop up with a "blurb" sound.)

Stylistic the design also has very less blue anymore, which may be liked or not. Maybe you can, however, try coloring the questions with another background color (like a light blue). That's also yet another thing you'll see in messengers.

What I may also think of is:
* maybe not display the "answer" of the user in a speech bubble. (analog to messengers input text fields, where also no bubble is there, until you send it)
* maybe try to connection the question to the selected POI/quest icon, i.e. "the house/building/... is asking this question". In such a caase, ou, may, however, of course also need to move the map and/or marker a bit differently, so it has space to display the speech bubble next to it.
  If you want to follow that path, it would be consequent to make the questions more personal, i.e. "_How many levels do I have?_", so that you more or less talk to the building. Pro/con: + less words, + gamification; - lacks seriousness

**Comment by rugk** [comment]
Here should be a fading inside of the bubble too, it looks very "cut off":

grafik

**Comment by rugk** [comment]
Generally I'd say it looks better for the "small height quests", than the street surface one, e.g. When you are almost in fullscreen, you may be better off with an actual, real full-screen look.

**Comment by westnordost** [comment]
> Here should be a fading inside of the bubble too, it looks very "cut off":

I tried that already (fade 8dp into white), did not look that good. It looked instead as if the bubble was 3D instead of flat. Basically the fadeout would be there to signal the user that he can scroll further there, but if he is at that point, he already knows. Same with scrolling down, because of the 1dp grey divider line towards the button.

> What I'd say would really matter in this design are the animations/transistions, how quests are shown etc. Because with chat bubbles, users assume a kind of animation they know from messengers etc. (see e.g. the advertisement videos for messengers, were these bubbles plop up with a "blurb" sound.)

Hmm, do you have a visual example?

> Or, e.g. get rid of the "arrow" of the speech bubble for the user answer, then you have more width, too.

That's also an idea. Another thing I thought of was to move the arrow from the side to the top for the question and to the bottom for the answer. Wastes a little (10dp) space, though, vertical space is not that valuable.

**Comment by rugk** [comment]
> Hmm, do you have a visual example? That would be interesting to see.

Not really the original aniomations I had in mind, but something like https://www.youtube.com/watch?v=JkwUSyW0ipo. I actually thought more of a slide from left/right into animation, but well...

In any case, I think what animation it is may not be important, but I guess to see a fitting one may be good. It makes it all just more fluent.

**Comment by SilentSpike** [comment]
Just to weigh in on a couple of points already covered:
- I think no longer having the blue background is a welcome change because that's the same colour as the top bar which clearly differentiates it from the map - this way quests feel more like you're directly interacting with something on the map.
- I would also have suggested removing the arrow from the user answer bubble because the arrow from the side commonly suggests a message sent in the past, but an arrow from the bottom could work too.
- I think ideally the question bubble would originate from the item of interest on the map so that when it mentions "**this** building/road/etc." it's clearly referring to it. One approach to this might be to have the arrow at the top in vertical orientation and at the right in horizontal orientation, then align the map so that the item of interest is above/on the right.

> If you want to follow that path, it would be consequent to make the questions more personal, i.e. "How many levels do I have?"

Personally not a fan of this idea because it's no longer clear what the question is asking about.

**Comment by Etua** [comment]
I don't really like how this top picture in surface quest is cut, leaving a few pixels of blank space there would improve it.

**Comment by claudiush** [comment]
I like the direction towards a more conversational app UI.
I was confused by the answer being formatted a a bubble as well as this indeed suggests it already has been "sent" into this conversation and cannot be altered. Interestingly enough e.g. WhatsApp also moved from styling the own answer input field as a bubble originating from the right to simply a rounded input field. I would suggest the same and have the answer box just styled as rounded rectangle.

Regarding the asking bubble originating from the map location: Keep in mind that the map is (and should stay) still scrollable during answering. So the speech bubble pointer need to dynamically point to the object in view (which would look awkward if the object is located at the top of the map view. I would suggest against it and leave the speech bubble pointer originating from top left of the rectangle.

**Comment by westnordost** [comment]
Okay, for the next iteration, I shall remove the speech bubble arrow of the answer bubble, make the answer bubble (almost) full width, move the speech bubble arrow of the question speech bubble to the top so that the question can also be almost full width and the arrow very roughly originates from the marker on the map and not from the left .

**Comment by westnordost** [comment]
device-2018-09-05-220124
device-2018-09-05-195450
device-2018-09-05-220346
device-2018-09-05-220248
device-2018-09-05-220203

**Comment by westnordost** [comment]
- close-button is back (top right corner, never View.GONE but INVISIBLE)
- when there is no content, only show the button bar
- dividers between the button bar buttons
- buttons in button bar stretch the whole width/height available (no margins)
- buttons in button bar are higher for better clickability
- fade speech bubble background to grey
- question title speechbubble has its arrow on the top now, stretches almost whole width
- answer speechbubble has no arrow, stretches almost whole width

By the way, did noone notice how cool the oneway-quest layout stretches the whole width and height of the bubble, even with the round corners? :-(

**Left to do:**
- experiment with a "more" indicator
- experiment with additional pop-in animation for speechbubbles
- experiment with animating speechbubbles to full width when the bottom sheet takes up the whole screen (removing horizontal margins)
- rework notes quest UI because it wíll look weird to display speechbubbles in speechbubbles
- experiment with giving the quest title speechbubble a more title-looking look

**Comment by rugk** [comment]
Looks great! :+1: 

> question title speechbubble has its arrow on the top now

As for that, looking at the images I got an idea (inspired by my previous ideas of set it nearby). You can keep it at that "arrow" same position, but I noticed that arrow "points somewhere":
45118112-c0d11880-b157-11e8-8836-55fdd55bb792
45118115-c0d11880-b157-11e8-976e-c754fa923729

As it's an "arrow" that is still what I associate with it. But could not you use a slight UI trick to change the shape of the small speech bubble arrow to point to the quest icon, i.e. in this direction:

45118115-c0d11880-b157-11e8-976e-c754fa923729
45118112-c0d11880-b157-11e8-8836-55fdd55bb792

I.e. change the "angle" of the arrow, so it looks like this (sorry, for that awful pixel manipulation – just hard to present this idea):

45118112-c0d11880-b157-11e8-8836-55fdd55bb792

> By the way, did noone notice how cool the oneway-quest layout stretches the whole width and height of the bubble, even with the round corners? :-(

Oh yeah, that **is indeed** great! The good thing about such slim design is you do not notice any problem with it and feel it is good…

**Comment by westnordost** [comment]
I find that too much effort for little effect.

**Comment by westnordost** [comment]
What do you think?
https://www.westnordost.de/misc/zoom-in-zoom-out.mp4

This is maybe a solution for a "you can scroll down here" indicator, because it briefly shows during the appear animation that there is more.

**Comment by rugk** [comment]
Except for the fact that the whole map flahes when you zoom out in the window, the animation looks quite good.

Did you use [the "Decelerate easing" (for incoming elements)](https://material.io/design/motion/speed.html#easing-figure-caption-1) (and [possible the "large" ones for animation duration](https://material.io/design/motion/speed.html#duration-figure-caption-7)?

**Comment by ENT8R** [comment]
Looks pretty nice IMO... I will try to test it a little bit this weekend :smile:

**Comment by JayTurnr** [comment]
Beta tester on app, made aware of this through Play Store. Not a fan of the bubbles UI. It's a violation of Material design and seems to take up more space than the old UI.

**Comment by westnordost** [comment]
What exactly is a violation of material design?

**Comment by rugk** [comment]
The final design with Screenshots in the Readme looks a little different.
What is the font you use for the titles there? It looks different and quite strong/a very dense – it's also not the one from the header image. (Would just like a consistent font/design system, especially when thinking of the future website.)

**Comment by rugk** [comment]
Why condensed though? Visually, it looks a bit "hard" to have condensed + bold font…? 

(also don't know what you answered with "yes" there. :wink: )

**Comment by rugk** [comment]
Another question: As for the notes discussion view, can SC fetch the OSM avatars there, if available, instead of just showing the placeholders, as it can be seen in the Reaadme?

**Comment by ENT8R** [comment]
The real OSM avatars are already used, they are just not visible in the screenshots...

**Comment by rugk** [comment]
Great! :smiley: (though real ones, maybe with @westnordost may look nicer in the screensshots :wink:)

**Pull request merged**
