### PR TITLE
ask about footway part of segregated way

### LINKED ISSUE #1489: Ask about cycleway/footway surface
### General
Affected tag(s) to be modified/added: [cycleway:surface](https://wiki.openstreetmap.org/wiki/Key%3Acycleway%3Asurface), [footway:surface](https://wiki.openstreetmap.org/wiki/Key%3Afootway%3Asurface)

Question asked: **What is the surface of bicycle part of this way?** + **What is the surface of pedestrian part of this way?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam) (though is some regions it may be asphalt over and over again for cycleway part, but it should not be worse that standard `surface` quest)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) - is 8000 elements worldwide enough? http://overpass-turbo.eu/s/KYI

### Ideas for implementation

**Element selection:** http://overpass-turbo.eu/s/KYK

**Metadata needed:** no

**Proposed GUI:** reuse existing surface GUI

I consider it as one of steps toward #279 ("add quest to make surface=paved/unpaved more detailed")

### PR DESCRIPTION
**Pull request by matkoniecz**
together with #1493 fixes #1489

-----

My work on this pull request and UX testing was sponsored by a NGI Zero Discovery [grant](https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/368849)

### CODE REVIEW

**Comment by matkoniecz** [comment]
Note - it has no pretty special icon. I may try adding one (but it is unlikely to be great, even if made from already available parts).

**Comment by westnordost** [comment]
Ok I made you an icon

**Comment by matkoniecz** [comment]
Thanks!

**Comment by matkoniecz** [comment]
version with icon available

**Pull request merged**
