### PR TITLE
log quest solvings, fixes #829

### LINKED ISSUE #829: Quest solvings should be written to Logcat
I've created my first pull request for a new quest and I've noticed some things that aren't so nice, for example, it should be the case that replies to quests are written in Logcat so that you can test the change without giving the test app access and without uploading the change to OSM.

### PR DESCRIPTION
**Pull request by matkoniecz**
it makes debugging easier (solving + undoing quest in offline mode is also showing tag edits that would happen)

### CODE REVIEW

**Comment by rugk** [comment]
You need to put that "fixes …" into the PR body, not title for GitHub to recognize that…

**Comment by exploide** [comment]
Not if the commit message itself also includes the fixes line ;)

**Comment by rugk** [comment]
Then GitHub shows shows [this](https://github.com/westnordost/StreetComplete/issues/829):
image

That, however, will not auto-close the issue once the PR is merged. It is merely just a "mention" you could also do in any other commit.

**Comment by exploide** [comment]
Sorry for continuing this offtopic discussion, but to cite the following GitHub help page https://help.github.com/articles/closing-issues-using-keywords/

> You can include keywords in your pull request titles and descriptions, as well as commit messages, to automatically close issues in GitHub.

You may also hover that info icon your screenshot shows.

**Comment by westnordost** [comment]
These recurring remarks annoy me a little. I rather have to close a bug manually than read through this kind of cruft when I review a PR. What is important is the code.

**Comment by westnordost** [comment]
The `StringMapChangesBuilder.java` should remain free of (Android) dependencies.  The logging would need to take place on another level, i.e. in `QuestController`

**Pull request closed without merging**
