### PR TITLE
Quest camera type

### PR DESCRIPTION
**Pull request by Binnette**
Hi, here a new quest type "camera_type" :

- it looks for nodes with surveillance:type=camera and !camera:type
- on quest tap, It shows 3 answers :+1:  dome, fixed or panning (only 1 is accepted)
- on confirm, it add a value for attribute camera:type of the OSM node

 Questions :
- @matkoniecz : do I have to add an "OR" (or may be an "AND") to include nodes with man_made=surveillance ?
- @westnordost : can I implement a "multiple page response form" ? Page 1, I ask for camera:type dome/fixed/panning; Page 2, I ask for camera:mount pole/wall. Is this possible or already existing in SC ?

Here is my current screenshot (with my ugly icons) :
screenshot_20170606-223326

----

And here is a "proof", that it is working great :
2017-06-06 23_18_57-openstreetmap _ noeud _ 3825613345

### CODE REVIEW

**Comment by matkoniecz** [comment]
https://github.com/westnordost/StreetComplete/blob/00b5d17af222a73b84c9b7eb733a34e42e61d1d0/app/src/main/java/de/westnordost/streetcomplete/data/osm/tql/FiltersParser.java creates overpass queries, but I am not fully understanding it.

**Comment by matkoniecz** [comment]
Note that http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance has "A surveillance camera or other types of surveillance equipment." - so asking for camera:type seems to be ensuring unwanted false positives.

**Comment by Binnette** [comment]
For more info, here are the documentation :

- [man_made:surveillance](https://wiki.openstreetmap.org/wiki/FR:Tag:man_made%3Dsurveillance)
- [camera:type](https://wiki.openstreetmap.org/wiki/Proposed_features/Extended_tags_for_Key:Surveillance#Camera)

**Comment by westnordost** [comment]
Hm, this is only a proposed feature. I do not want to push unapproved tags with this app as this should be a community decision. 

As a developer creating software for OSM, one has quite some power to establish and/or deprecate certain tagging by simply implementing / interpreting the data in a certain way. I think it is important to not misuse that power but instead keep in mind that the OSM is a community driven project. What is your opinion on that?

> @westnordost : can I implement a "multiple page response form" ? Page 1, I ask for camera:type dome/fixed/panning; Page 2, I ask for camera:mount pole/wall. Is this possible or already existing in SC ?
Two pages should be two quests. The app follows the UI pattern: 1 quest, 1 information added. Thus, a two-paged quest does not exist.

**Comment by Binnette** [comment]
You are definitively right ! :+1: 
So i close my pull request and keep it for later.

Thanks for the details about the "two page quest" system.

**Pull request closed without merging**
