### PR TITLE
ask about toilet availability in name=McDonald's [+fixing quest-breaking bug]

### PR DESCRIPTION
**Pull request by matkoniecz**
McDonald's are likely to include toilets, it is OK to go inside like to department store or mall (at least from my experience).

At the same time mass edit without ground survey blindly adding toilets=yes to all McDonald's would not be appropriate.

### CODE REVIEW

**Comment by matkoniecz** [comment]
I added also second commit here that fixes bug in filtering (quest was adding toilet**s** tag and checking presence of toilet tag)

add here rather as a separate PR to avoid merge conflicts

**Comment by HolgerJeromin** [comment]
What about Burger King? Or other fast food restaurants?
Do we really want a white list of some restaurant brands which are "known to have a free toilet"

I am not sure if the operators of these restaurants would be too happy.

**Comment by matkoniecz** [comment]
> What about Burger King? Or other fast food restaurants?

I have no idea whatever it would make sense.

>  Do we really want a white list of some restaurant brands which are "known to have a free toilet"

That is the first condition, second one is that entering them is similar to entering other private-owned public spaces like malls.

**Comment by krzyk** [comment]
> Do we really want a white list of some restaurant brands which are "known to have a free toilet"

Why do you wrote "free toilet"? Toiled in McDonnald is not free, it is free only to customers, you have to show receipt to enter.

**Comment by rugk** [comment]
That would be `access=customers`…

**Comment by Phyks** [comment]
> Why do you wrote "free toilet"? Toilet in McDonnald is free only to customers, you have to show receipt to enter.

Depends on the McDonalds. From my experience (in France), some have open free toilets, others require you to type a code printed on your receipt.

**Comment by rugk** [comment]
So then this is a useful quest to ask the user. "Does it have a toilet?" "For customers only" | "For everybody" | "No"

**Comment by HolgerJeromin** [comment]
BTW that would be `toilets:access` ([taginfo](https://taginfo.openstreetmap.org/keys/toilets%3Aaccess)) as we dont want to tag the access of the restaurant.

**Comment by westnordost** [comment]
Too specific.

Thank you for the note regarding the quest-breaking mistake in the overpass query though.

**Pull request closed without merging**
