### PR TITLE
Add landuse to name Quest

### PR DESCRIPTION
**Pull request by wvanderp**
This pullreqest adds landuse to the name quest.

i've selected "cemetery", "allotments", "recreation_ground",  "military", "quarry" for this quest.

i think these are the few landuses which always have an name.

open to feedback and revision request

### CODE REVIEW

**Comment by westnordost** [comment]
That's a good idea! Maybe also add public parks? 

**However**, the deciding factor is not if that landuse will usually have a name, but if it can be expected that (at the entrance to) this landuse there will be a sign denoting the name. Otherwise, surveyors will tag it incorrectly as `noname=yes` just because they do not see a sign.

Would you please revise the list to include only those landuses where one would expect a sign (at the entrance)?

**Comment by wvanderp** [comment]
Then I would change it as follows:

Things with a name:
- cemetery

Things which might have a name:
- allotments
- some military

things which might be difficult
- quarry
- recreation_ground

So, what I propose is to add cemetery and allotments and add military under the military tags

**Comment by westnordost** [comment]
Sounds good!

**Comment by westnordost** [comment]
Good, thank you!

**Comment by matkoniecz** [comment]
Note #2186 requesting to never ask for names of cemeteries and allotments

**Pull request merged**
