### PR TITLE
Losslessly optimized non-vector images

### PR DESCRIPTION
**Pull request by stefanb**
Saved 1,5 MB out of 11,3 MB. 13,4% overall (up to 72% per file) using ImageOptim.
This is excluding .svg images, which were also included in #817 and will be dealt with differently in #814.

image

### CODE REVIEW

**Comment by westnordost** [comment]
That's nice!

I guess, one might also think about whether converting all the images to WebP makes sense before trying to squeeze out more out of JPEG (with lossy optimization).

It is supported since Android 4.0. https://developer.android.com/guide/topics/media/media-formats.html#image-formats

**Comment by stefanb** [comment]
Well, od course other image optimisations are also possible, but they require either accepting some quality loss and/or code changes and must be done more carefully.

**Comment by goldfndr** [comment]
It looks to me like an additional 1.5 MB could be saved by removing the JPGs in the mdpi and hdpi directories, and leaving [just the xhdpi and xxhdpi directories](https://stackoverflow.com/a/19196749): *"Is shipping only xxhdpi and xhdpi an alternative?" -- only if your `minSdkVersion` is 8 or higher.* Given that the images were scaled down anyway, they might not look so bad.

**Comment by matkoniecz** [comment]
Note "Now, whether you like the look of your downsampled drawables is another matter entirely" part.

**Comment by stefanb** [comment]
When images are bad enough they cannot be degraded any further by Android downsampling :)
With this in mind some lossy compression could be applied, eg
* inreasing jpeg compression ratio
* applying perceptual compression https://github.com/google/guetzli
* changing image types where applicable

...but care must be taken that such lossy compression is not applied multiple times on the same images.

**Pull request merged**
