### PR TITLE
Add parking type quest

### PR DESCRIPTION
**Pull request by ENT8R**
This PR adds a new quest to determine the type of a parking area. This quest was requested in #331.
It looks like this:

I hope you like it 😄

### CODE REVIEW

**Comment by ENT8R** [comment]
What about this one?

**Comment by ENT8R** [comment]
This image is now added and there are titles on top of every image.

**Comment by westnordost** [comment]
Hm, I think the image is not good because only the upper right quarter shows the actual parking entrance and that not very well.

The "leading actor" of the image should be the underground parking entrance. What constitutes a typical underground parking entrance? That it goes down, that there is an entrance and an exit (usually), that there are signs that show allowances like max height/width/etc and that there are entry/exit controls (vending machines, lift gates) (usually).

Some pictures (just to illustrate the point, they do not have a fitting license):
https://thumbs.dreamstime.com/x/car-park-entrance-underground-entry-hospital-additional-cost-33080775.jpg
http://www.nerjatoday.com/wp-content/uploads/municipalcarpark.jpg
https://thumbs.dreamstime.com/z/entrance-to-underground-parking-german-garage-germany-47409630.jpg

**Comment by ENT8R** [comment]
This one?

**Comment by westnordost** [comment]
Looks good

**Comment by westnordost** [comment]
Make sure to crop it so that the important things are in the picture

**Comment by ENT8R** [comment]
OK. I will do this today!

_Sent from my Samsung GT-I9300 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ENT8R** [comment]
This is how it looks now:


Is that OK?

**Pull request merged**
